import type { Verse, Connection, Chapter } from './types.js';

export const chapters: Chapter[] = [
  { number: 1, title: "Arjuna's Dilemma", titleSanskrit: 'Arjuna Vishada Yoga', verses: 47, theme: 'The despair and moral crisis of Arjuna' },
  { number: 2, title: 'The Eternal Self', titleSanskrit: 'Sankhya Yoga', verses: 72, theme: 'Knowledge of the imperishable soul' },
  { number: 3, title: 'Path of Action', titleSanskrit: 'Karma Yoga', verses: 43, theme: 'The yoga of selfless action' },
  { number: 4, title: 'Wisdom & Renunciation', titleSanskrit: 'Jnana Karma Sannyasa Yoga', verses: 42, theme: 'Divine knowledge and the purpose of action' },
  { number: 5, title: 'Renunciation of Action', titleSanskrit: 'Karma Sannyasa Yoga', verses: 29, theme: 'True renunciation through action' },
  { number: 6, title: 'Meditation', titleSanskrit: 'Dhyana Yoga', verses: 47, theme: 'The practice of meditation and self-control' },
  { number: 7, title: 'Knowledge & Wisdom', titleSanskrit: 'Jnana Vijnana Yoga', verses: 30, theme: 'Understanding the absolute truth' },
  { number: 8, title: 'The Imperishable Brahman', titleSanskrit: 'Aksara Brahma Yoga', verses: 28, theme: 'The path to the eternal' },
  { number: 9, title: 'Royal Knowledge', titleSanskrit: 'Raja Vidya Raja Guhya Yoga', verses: 34, theme: 'The sovereign science and sovereign secret' },
  { number: 10, title: 'Divine Manifestations', titleSanskrit: 'Vibhuti Yoga', verses: 42, theme: 'The opulence of the Absolute' },
  { number: 11, title: 'Universal Form', titleSanskrit: 'Visvarupa Darsana Yoga', verses: 55, theme: 'The vision of the cosmic form' },
  { number: 12, title: 'Devotion', titleSanskrit: 'Bhakti Yoga', verses: 20, theme: 'The path of devotion' },
  { number: 13, title: 'Field & Knower', titleSanskrit: 'Ksetra Ksetrajna Vibhaga Yoga', verses: 35, theme: 'Distinguishing matter from spirit' },
  { number: 14, title: 'Three Modes', titleSanskrit: 'Gunatraya Vibhaga Yoga', verses: 27, theme: 'The three modes of material nature' },
  { number: 15, title: 'Supreme Person', titleSanskrit: 'Purusottama Yoga', verses: 20, theme: 'The yoga of the supreme person' },
  { number: 16, title: 'Divine & Demonic', titleSanskrit: 'Daivasura Sampad Vibhaga Yoga', verses: 24, theme: 'Divine and demoniac natures' },
  { number: 17, title: 'Three Types of Faith', titleSanskrit: 'Sraddhatraya Vibhaga Yoga', verses: 28, theme: 'The divisions of faith' },
  { number: 18, title: 'Liberation', titleSanskrit: 'Moksa Sannyasa Yoga', verses: 78, theme: 'The perfection of renunciation and surrender' },
];

export const verses: Verse[] = [
  {
    chapter: 2,
    verse: 47,
    id: '2.47',
    sanskrit: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥',
    transliteration: "karmaṇy-evādhikāras te mā phaleṣhu kadāchana, mā karma-phala-hetur bhūr mā te saṅgo 'stvakarmaṇi",
    translation: 'You have a right to perform your prescribed duty, but you are not entitled to the fruits of action. Never consider yourself the cause of the results of your activities, and never be attached to not doing your duty.',
    theme: 'Selfless Action',
    concepts: ['karma', 'detachment', 'duty', 'renunciation'],
  },
  {
    chapter: 3,
    verse: 19,
    id: '3.19',
    sanskrit: 'तस्मादसक्तः सततं कार्यं कर्म समाचर। असक्तो ह्याचरन्कर्म परमाप्नोति पूरुषः॥',
    transliteration: 'tasmād asaktaḥ satataṁ kāryaṁ karma samāchara, asakto hyācharan karma param āpnoti pūruṣaḥ',
    translation: 'Therefore, without being attached to the fruits of activities, one should act as a matter of duty, for by working without attachment one attains the Supreme.',
    theme: 'Path to Liberation',
    concepts: ['karma', 'detachment', 'liberation', 'duty'],
  },
  {
    chapter: 2,
    verse: 14,
    id: '2.14',
    sanskrit: 'मात्रास्पर्शास्तु कौन्तेय शीतोष्णसुखदुःखदाः। आगमापायिनोऽनित्यास्तांस्तितिक्षस्व भारत॥',
    transliteration: "mātrā-sparśhās tu kaunteya śhītoṣhṇa-sukha-duḥkha-dāḥ, āgamāpāyino 'nityās tāṁs titikṣhasva bhārata",
    translation: 'O son of Kunti, the contact between the senses and the sense objects gives rise to fleeting perceptions of happiness and distress. These are non-permanent, and come and go like the winter and summer seasons. O descendent of Bharat, one must learn to tolerate them without being disturbed.',
    theme: 'Equanimity',
    concepts: ['detachment', 'tolerance', 'impermanence', 'equanimity'],
  },
  {
    chapter: 6,
    verse: 5,
    id: '6.5',
    sanskrit: 'उद्धरेदात्मनात्मानं नात्मानमवसादयेत्। आत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः॥',
    transliteration: 'uddhared ātmanātmānaṁ nātmānam avasādayet, ātmaiva hyātmano bandhur ātmaiva ripur ātmanaḥ',
    translation: 'Elevate yourself through the power of your mind, and not degrade yourself, for the mind can be the friend and also the enemy of the self.',
    theme: 'Self-Mastery',
    concepts: ['self-discipline', 'meditation', 'mind-control', 'self-development'],
  },
  {
    chapter: 18,
    verse: 66,
    id: '18.66',
    sanskrit: 'सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज। अहं त्वा सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः॥',
    transliteration: 'sarva-dharmān parityajya mām ekaṁ śharaṇaṁ vraja, ahaṁ tvāṁ sarva-pāpebhyo mokṣhayiṣhyāmi mā śhuchaḥ',
    translation: 'Abandon all varieties of dharmas and simply surrender unto Me alone. I shall liberate you from all sinful reactions; do not fear.',
    theme: 'Complete Surrender',
    concepts: ['surrender', 'devotion', 'liberation', 'grace'],
  },
  {
    chapter: 4,
    verse: 7,
    id: '4.7',
    sanskrit: 'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत। अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥',
    transliteration: 'yadā yadā hi dharmasya glānir bhavati bhārata, abhyutthānam adharmasya tadātmānaṁ sṛijāmyaham',
    translation: 'Whenever there is a decline in righteousness and an increase in unrighteousness, O Arjuna, at that time I manifest Myself on earth.',
    theme: 'Divine Intervention',
    concepts: ['dharma', 'divine-incarnation', 'protection', 'cosmic-order'],
  },
  {
    chapter: 9,
    verse: 22,
    id: '9.22',
    sanskrit: 'अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते। तेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम्॥',
    transliteration: 'ananyāśh chintayanto māṁ ye janāḥ paryupāsate, teṣhāṁ nityābhiyuktānāṁ yoga-kṣhemaṁ vahāmyaham',
    translation: 'To those who worship Me with exclusive devotion, meditating on My transcendental form—to them I carry what they lack and preserve what they have.',
    theme: 'Divine Care',
    concepts: ['devotion', 'faith', 'divine-protection', 'surrender'],
  },
  {
    chapter: 12,
    verse: 13,
    id: '12.13',
    sanskrit: 'अद्वेष्टा सर्वभूतानां मैत्रः करुण एव च। निर्ममो निरहङ्कारः समदुःखसुखः क्षमी॥',
    transliteration: 'adveṣhṭā sarva-bhūtānāṁ maitraḥ karuṇa eva cha, nirmamo nirahaṅkāraḥ sama-duḥkha-sukhaḥ kṣhamī',
    translation: 'One who is not envious but is a kind friend to all living entities, who does not think himself a proprietor and is free from false ego, who is equal in both happiness and distress, and who is always satisfied and forgiving.',
    theme: 'Qualities of a Devotee',
    concepts: ['compassion', 'equanimity', 'humility', 'forgiveness'],
  },
  {
    chapter: 2,
    verse: 62,
    id: '2.62',
    sanskrit: 'ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते। सङ्गात्सञ्जायते कामः कामात्क्रोधोऽभिजायते॥',
    transliteration: "dhyāyato viṣhayān puṁsaḥ saṅgas teṣhūpajāyate, saṅgāt sañjāyate kāmaḥ kāmāt krodho 'bhijāyate",
    translation: 'While contemplating the objects of the senses, a person develops attachment for them, and from such attachment lust develops, and from lust anger arises.',
    theme: 'Downward Spiral',
    concepts: ['desire', 'attachment', 'anger', 'self-destruction'],
  },
  {
    chapter: 2,
    verse: 63,
    id: '2.63',
    sanskrit: 'क्रोधाद्भवति सम्मोहः सम्मोहात्स्मृतिविभ्रमः। स्मृतिभ्रंशाद् बुद्धिनाशो बुद्धिनाशात्प्रणश्यति॥',
    transliteration: 'krodhād bhavati sammohaḥ sammohāt smṛiti-vibhramaḥ, smṛiti-bhranśhād buddhi-nāśho buddhi-nāśhāt praṇaśhyati',
    translation: 'From anger, complete delusion arises, and from delusion bewilderment of memory. When memory is bewildered, intelligence is lost, and when intelligence is lost one falls down again into the material pool.',
    theme: 'Path to Ruin',
    concepts: ['anger', 'delusion', 'destruction', 'self-control'],
  },
  {
    chapter: 5,
    verse: 10,
    id: '5.10',
    sanskrit: 'ब्रह्मण्याधाय कर्माणि सङ्गं त्यक्त्वा करोति यः। लिप्यते न स पापेन पद्मपत्रमिवाम्भसा॥',
    transliteration: 'brahmaṇy ādhāya karmāṇi saṅgaṁ tyaktvā karoti yaḥ, lipyate na sa pāpena padma-patram ivāmbhasā',
    translation: 'One who performs their duty without attachment, surrendering the results unto the Supreme Lord, is unaffected by sinful action, as the lotus leaf is untouched by water.',
    theme: 'Detached Action',
    concepts: ['karma', 'detachment', 'purity', 'surrender'],
  },
  {
    chapter: 3,
    verse: 27,
    id: '3.27',
    sanskrit: 'प्रकृतेः क्रियमाणानि गुणैः कर्माणि सर्वशः। अहङ्कारविमूढात्मा कर्ताहमिति मन्यते॥',
    transliteration: 'prakṛiteḥ kriyamāṇāni guṇaiḥ karmāṇi sarvaśhaḥ, ahaṅkāra-vimūḍhātmā kartāham iti manyate',
    translation: 'All activities are carried out by the three modes of material nature. But in ignorance, the soul, deluded by false identification with the body, thinks itself to be the doer.',
    theme: 'False Ego',
    concepts: ['ego', 'illusion', 'modes-of-nature', 'self-knowledge'],
  },
  {
    chapter: 6,
    verse: 35,
    id: '6.35',
    sanskrit: 'असंशयं महाबाहो मनो दुर्निग्रहं चलम्। अभ्यासेन तु कौन्तेय वैराग्येण च गृह्यते॥',
    transliteration: 'asanśhayaṁ mahā-bāho mano durnigrahaṁ chalam, abhyāsena tu kaunteya vairāgyeṇa cha gṛihyate',
    translation: 'Undoubtedly, O mighty-armed one, the mind is restless and difficult to restrain, but it is subdued by practice and by detachment.',
    theme: 'Mind Control',
    concepts: ['meditation', 'practice', 'detachment', 'self-discipline'],
  },
  {
    chapter: 7,
    verse: 14,
    id: '7.14',
    sanskrit: 'दैवी ह्येषा गुणमयी मम माया दुरत्यया। मामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते॥',
    transliteration: 'daivī hyeṣhā guṇa-mayī mama māyā duratyayā, mām eva ye prapadyante māyām etāṁ taranti te',
    translation: 'This divine energy of Mine, consisting of the three modes of material nature, is difficult to overcome. But those who have surrendered unto Me can easily cross beyond it.',
    theme: 'Transcending Illusion',
    concepts: ['maya', 'surrender', 'liberation', 'divine-grace'],
  },
  {
    chapter: 13,
    verse: 8,
    id: '13.8',
    sanskrit: 'अमानित्वमदम्भित्वमहिंसा क्षान्तिरार्जवम्। आचार्योपासनं शौचं स्थैर्यमात्मविनिग्रहः॥',
    transliteration: 'amānitvam adambhitvam ahiṁsā kṣhāntir ārjavam, āchāryopāsanaṁ śhauchaṁ sthairyam ātma-vinigrahaḥ',
    translation: 'Humility, unpretentiousness, non-violence, forgiveness, simplicity, service to the teacher, cleanliness, steadfastness, and self-control.',
    theme: 'Spiritual Qualities',
    concepts: ['humility', 'non-violence', 'self-control', 'wisdom'],
  },
  {
    chapter: 4,
    verse: 38,
    id: '4.38',
    sanskrit: 'न हि ज्ञानेन सदृशं पवित्रमिह विद्यते। तत्स्वयं योगसंसिद्धः कालेनात्मनि विन्दति॥',
    transliteration: 'na hi jñānena sadṛiśhaṁ pavitramiha vidyate, tat svayaṁ yoga-sansiddhaḥ kālenātmani vindati',
    translation: 'In this world, there is nothing as purifying as divine knowledge. One who has attained purity of mind through prolonged practice of Yoga, receives such knowledge within the heart, in due course of time.',
    theme: 'Supreme Knowledge',
    concepts: ['knowledge', 'purity', 'yoga', 'self-realization'],
  },
  {
    chapter: 15,
    verse: 7,
    id: '15.7',
    sanskrit: 'ममैवांशो जीवलोके जीवभूतः सनातनः। मनःषष्ठानीन्द्रियाणि प्रकृतिस्थानि कर्षति॥',
    transliteration: 'mamaivānśho jīva-loke jīva-bhūtaḥ sanātanaḥ, manaḥ-ṣhaṣhṭhānīndriyāṇi prakṛiti-sthāni karṣhati',
    translation: 'The embodied souls in this material world are My eternal fragmental parts. But bound by material nature, they are struggling with the six senses including the mind.',
    theme: 'Eternal Soul',
    concepts: ['soul', 'divine-nature', 'bondage', 'struggle'],
  },
  {
    chapter: 9,
    verse: 27,
    id: '9.27',
    sanskrit: 'यत्करोषि यदश्नासि यज्जुहोषि ददासि यत्। यत्तपस्यसि कौन्तेय तत्कुरुष्व मदर्पणम्॥',
    transliteration: 'yat karoṣhi yad aśhnāsi yaj juhoṣhi dadāsi yat, yat tapasyasi kaunteya tat kuruṣhva mad-arpaṇam',
    translation: 'Whatever you do, whatever you eat, whatever you offer in sacrifice, whatever you give away, and whatever austerities you perform, O son of Kunti, do it as an offering to Me.',
    theme: 'Dedication to Divine',
    concepts: ['devotion', 'surrender', 'offering', 'dedication'],
  },
  {
    chapter: 1,
    verse: 1,
    id: '1.1',
    sanskrit: 'धृतराष्ट्र उवाच। धर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः। मामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय॥',
    transliteration: 'dhṛitarāśhtra uvācha, dharma-kṣhetre kuru-kṣhetre samavetā yuyutsavaḥ, māmakāḥ pāṇḍavāśh chaiva kimakurvata sañjaya',
    translation: 'Dhritarashtra said: O Sanjaya, what did my sons and the sons of Pandu do when they assembled on the sacred field of Kurukshetra, eager for battle?',
    theme: 'The Beginning',
    concepts: ['dharma', 'battlefield', 'conflict', 'duty'],
  },
  {
    chapter: 1,
    verse: 47,
    id: '1.47',
    sanskrit: 'एवमुक्त्वार्जुनः सङ्ख्ये रथोपस्थ उपाविशत्। विसृज्य सशरं चापं शोकसंविग्नमानसः॥',
    transliteration: 'evam uktvārjunaḥ saṅkhye rathopastha upāviśhat, visṛijya saśharaṁ chāpaṁ śhoka-saṁvigna-mānasaḥ',
    translation: 'Having spoken thus on the battlefield, Arjuna cast aside his bow and arrows, and sat down on the seat of his chariot, his mind overwhelmed with grief.',
    theme: 'Arjuna\'s Despair',
    concepts: ['grief', 'confusion', 'moral-crisis', 'surrender'],
  },
  {
    chapter: 2,
    verse: 20,
    id: '2.20',
    sanskrit: 'न जायते म्रियते वा कदाचिन्नायं भूत्वा भविता वा न भूयः। अजो नित्यः शाश्वतोऽयं पुराणो न हन्यते हन्यमाने शरीरे॥',
    transliteration: "na jāyate mriyate vā kadāchin nāyaṁ bhūtvā bhavitā vā na bhūyaḥ, ajo nityaḥ śhāśhvato 'yaṁ purāṇo na hanyate hanyamāne śharīre",
    translation: 'The soul is never born and never dies. Having come into being once, it never ceases to be. It is unborn, eternal, ever-existing, and primeval. It is not slain when the body is slain.',
    theme: 'Eternal Nature of Soul',
    concepts: ['soul', 'immortality', 'self-knowledge', 'eternal'],
  },
  {
    chapter: 2,
    verse: 56,
    id: '2.56',
    sanskrit: 'दुःखेष्वनुद्विग्नमनाः सुखेषु विगतस्पृहः। वीतरागभयक्रोधः स्थितधीर्मुनिरुच्यते॥',
    transliteration: 'duḥkheṣhv-anudvigna-manāḥ sukheṣhu vigata-spṛihaḥ, vīta-rāga-bhaya-krodhaḥ sthita-dhīr munir uchyate',
    translation: 'One whose mind remains undisturbed amidst misery, who does not crave for pleasure, and who is free from attachment, fear, and anger, is called a sage of steady wisdom.',
    theme: 'Steady Wisdom',
    concepts: ['equanimity', 'detachment', 'peace', 'wisdom'],
  },
  {
    chapter: 3,
    verse: 5,
    id: '3.5',
    sanskrit: 'न हि कश्चित्क्षणमपि जातु तिष्ठत्यकर्मकृत्। कार्यते ह्यवशः कर्म सर्वः प्रकृतिजैर्गुणैः॥',
    transliteration: 'na hi kaśhchit kṣhaṇam api jātu tiṣhṭhatyakarma-kṛit, kāryate hyavaśhaḥ karma sarvaḥ prakṛiti-jair guṇaiḥ',
    translation: 'No one can remain without action even for a moment. Everyone is compelled to act by the qualities born of material nature.',
    theme: 'Nature of Action',
    concepts: ['karma', 'nature', 'action', 'compulsion'],
  },
  {
    chapter: 3,
    verse: 35,
    id: '3.35',
    sanskrit: 'श्रेयान्स्वधर्मो विगुणः परधर्मात्स्वनुष्ठितात्। स्वधर्मे निधनं श्रेयः परधर्मो भयावहः॥',
    transliteration: 'śhreyān swa-dharmo viguṇaḥ para-dharmāt sv-anuṣhṭhitāt, swa-dharme nidhanaṁ śhreyaḥ para-dharmo bhayāvahaḥ',
    translation: 'It is better to perform one\'s own duty imperfectly than to perform another\'s duty perfectly. It is better to die in the discharge of one\'s own duty; the duty of another is fraught with danger.',
    theme: 'Own Duty',
    concepts: ['dharma', 'duty', 'authenticity', 'self'],
  },
  {
    chapter: 4,
    verse: 18,
    id: '4.18',
    sanskrit: 'कर्मण्यकर्म यः पश्येदकर्मणि च कर्म यः। स बुद्धिमान्मनुष्येषु स युक्तः कृत्स्नकर्मकृत्॥',
    transliteration: 'karmaṇy akarma yaḥ paśhyed akarmaṇi cha karma yaḥ, sa buddhimān manuṣhyeṣhu sa yuktaḥ kṛitsna-karma-kṛit',
    translation: 'Those who see action in inaction and inaction in action are truly wise amongst humans. They are yogis, having accomplished all actions.',
    theme: 'Wisdom in Action',
    concepts: ['karma', 'wisdom', 'understanding', 'yoga'],
  },
  {
    chapter: 5,
    verse: 18,
    id: '5.18',
    sanskrit: 'विद्याविनयसम्पन्ने ब्राह्मणे गवि हस्तिनि। शुनि चैव श्वपाके च पण्डिताः समदर्शिनः॥',
    transliteration: 'vidyā-vinaya-sampanne brāhmaṇe gavi hastini, śhuni chaiva śhva-pāke cha paṇḍitāḥ sama-darśhinaḥ',
    translation: 'The truly learned, with the eyes of divine knowledge, see with equal vision a learned scholar, a cow, an elephant, a dog, and a dog-eater.',
    theme: 'Equal Vision',
    concepts: ['equality', 'wisdom', 'vision', 'discrimination'],
  },
  {
    chapter: 6,
    verse: 17,
    id: '6.17',
    sanskrit: 'युक्ताहारविहारस्य युक्तचेष्टस्य कर्मसु। युक्तस्वप्नावबोधस्य योगो भवति दुःखहा॥',
    transliteration: 'yuktāhāra-vihārasya yukta-cheṣhṭasya karmasu, yukta-svapnāvabodhasya yogo bhavati duḥkha-hā',
    translation: 'Those who are temperate in eating and recreation, balanced in work, and regulated in sleep, can mitigate all sorrows by practicing yoga.',
    theme: 'Balance in Life',
    concepts: ['balance', 'moderation', 'yoga', 'discipline'],
  },
  {
    chapter: 7,
    verse: 7,
    id: '7.7',
    sanskrit: 'मत्तः परतरं नान्यत्किञ्चिदस्ति धनञ्जय। मयि सर्वमिदं प्रोतं सूत्रे मणिगणा इव॥',
    transliteration: 'mattaḥ parataraṁ nānyat kiñchid asti dhanañjaya, mayi sarvam idaṁ protaṁ sūtre maṇi-gaṇā iva',
    translation: 'There is nothing higher than Me, O Arjuna. Everything rests upon Me, as pearls are strung on a thread.',
    theme: 'Supreme Reality',
    concepts: ['divine', 'unity', 'supreme', 'connection'],
  },
  {
    chapter: 8,
    verse: 5,
    id: '8.5',
    sanskrit: 'अन्तकाले च मामेव स्मरन्मुक्त्वा कलेवरम्। यः प्रयाति स मद्भावं याति नास्त्यत्र संशयः॥',
    transliteration: 'anta-kāle cha mām eva smaran muktvā kalevaram, yaḥ prayāti sa mad-bhāvaṁ yāti nāstyatra sanśhayaḥ',
    translation: 'Whoever departs from the body remembering Me alone at the time of death attains My nature. Of this, there is no doubt.',
    theme: 'Final Thought',
    concepts: ['death', 'remembrance', 'devotion', 'liberation'],
  },
  {
    chapter: 10,
    verse: 20,
    id: '10.20',
    sanskrit: 'अहमात्मा गुडाकेश सर्वभूताशयस्थितः। अहमादिश्च मध्यं च भूतानामन्त एव च॥',
    transliteration: 'aham ātmā guḍākeśha sarva-bhūtāśhaya-sthitaḥ, aham ādiśh cha madhyaṁ cha bhūtānām anta eva cha',
    translation: 'I am the Self, O Arjuna, seated in the hearts of all beings. I am the beginning, the middle, and the end of all beings.',
    theme: 'Divine Presence',
    concepts: ['divine', 'self', 'omnipresence', 'unity'],
  },
  {
    chapter: 11,
    verse: 54,
    id: '11.54',
    sanskrit: 'भक्त्या त्वनन्यया शक्य अहमेवंविधोऽर्जुन। ज्ञातुं द्रष्टुं च तत्त्वेन प्रवेष्टुं च परन्तप॥',
    transliteration: "bhaktyā tvananyayā śhakya aham evaṁ-vidho 'rjuna, jñātuṁ draṣhṭuṁ cha tattvena praveṣhṭuṁ cha parantapa",
    translation: 'Only by exclusive devotion can I be known and seen in this form, and entered into, O Arjuna.',
    theme: 'Devotional Path',
    concepts: ['devotion', 'vision', 'realization', 'unity'],
  },
  {
    chapter: 12,
    verse: 8,
    id: '12.8',
    sanskrit: 'मय्येव मन आधत्स्व मयि बुद्धिं निवेशय। निवसिष्यसि मय्येव अत ऊर्ध्वं न संशयः॥',
    transliteration: 'mayy eva mana ādhatsva mayi buddhiṁ niveśhaya, nivasiṣhyasi mayy eva ata ūrdhvaṁ na sanśhayaḥ',
    translation: 'Fix your mind on Me alone and let your intellect dwell upon Me. Thereafter you shall surely live in Me. Of this there is no doubt.',
    theme: 'Single-pointed Focus',
    concepts: ['concentration', 'devotion', 'mind-control', 'union'],
  },
  {
    chapter: 14,
    verse: 22,
    id: '14.22',
    sanskrit: 'प्रकाशं च प्रवृत्तिं च मोहमेव च पाण्डव। न द्वेष्टि सम्प्रवृत्तानि न निवृत्तानि काङ्क्षति॥',
    transliteration: 'prakāśhaṁ cha pravṛittiṁ cha moham eva cha pāṇḍava, na dveṣhṭi sampravṛittāni na nivṛittāni kāṅkṣhati',
    translation: 'O Pandava, those who do not hate illumination, activity, and delusion when they are present, nor long for them when they disappear.',
    theme: 'Beyond Modes',
    concepts: ['transcendence', 'detachment', 'equanimity', 'freedom'],
  },
  {
    chapter: 16,
    verse: 1,
    id: '16.1',
    sanskrit: 'अभयं सत्त्वसंशुद्धिर्ज्ञानयोगव्यवस्थितिः। दानं दमश्च यज्ञश्च स्वाध्यायस्तप आर्जवम्॥',
    transliteration: 'abhayaṁ sattva-sanśhuddhir jñāna-yoga-vyavasthitiḥ, dānaṁ damaśh cha yajñaśh cha svādhyāyas tapa ārjavam',
    translation: 'Fearlessness, purity of heart, steadfastness in knowledge and yoga, charity, self-control, sacrifice, study of scriptures, austerity, and straightforwardness.',
    theme: 'Divine Qualities',
    concepts: ['virtues', 'righteousness', 'character', 'divinity'],
  },
  {
    chapter: 17,
    verse: 3,
    id: '17.3',
    sanskrit: 'सत्त्वानुरूपा सर्वस्य श्रद्धा भवति भारत। श्रद्धामयोऽयं पुरुषो यो यच्छ्रद्धः स एव सः॥',
    transliteration: "sattvānurūpā sarvasya śhraddhā bhavati bhārata, śhraddhā-mayo 'yaṁ puruṣho yo yach-chhraddhaḥ sa eva saḥ",
    translation: 'The faith of each person conforms to their nature, O Arjuna. Human beings are made of faith; as one\'s faith is, so one is.',
    theme: 'Nature of Faith',
    concepts: ['faith', 'nature', 'character', 'identity'],
  },
  {
    chapter: 18,
    verse: 46,
    id: '18.46',
    sanskrit: 'यतः प्रवृत्तिर्भूतानां येन सर्वमिदं ततम्। स्वकर्मणा तमभ्यर्च्य सिद्धिं विन्दति मानवः॥',
    transliteration: 'yataḥ pravṛittir bhūtānāṁ yena sarvam idaṁ tatam, swa-karmaṇā tam abhyarchya siddhiṁ vindati mānavaḥ',
    translation: 'By performing one\'s natural occupation, one worships the Creator from whom all beings originate and by whom all this universe is pervaded. By such performance, a person attains perfection.',
    theme: 'Worship Through Work',
    concepts: ['duty', 'worship', 'perfection', 'service'],
  },
  {
    chapter: 18,
    verse: 78,
    id: '18.78',
    sanskrit: 'यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः। तत्र श्रीर्विजयो भूतिर्ध्रुवा नीतिर्मतिर्मम॥',
    transliteration: 'yatra yogeśhvaraḥ kṛiṣhṇo yatra pārtho dhanur-dharaḥ, tatra śhrīr vijayo bhūtir dhruvā nītir matir mama',
    translation: 'Wherever there is Krishna, the Lord of Yoga, and wherever there is Arjuna, the wielder of the bow, there will also certainly be prosperity, victory, happiness, and righteousness. Of this, I am sure.',
    theme: 'Final Assurance',
    concepts: ['victory', 'righteousness', 'divine-grace', 'conclusion'],
  },
];

export const connections: Connection[] = [
  {
    from: '2.47',
    to: '3.19',
    type: 'thematic',
    description: 'Both verses emphasize performing duty without attachment to results',
    strength: 9,
  },
  {
    from: '2.47',
    to: '5.10',
    type: 'conceptual',
    description: 'Expanded teaching on detached action and remaining untouched by karma',
    strength: 8,
  },
  {
    from: '2.14',
    to: '12.13',
    type: 'practical',
    description: 'Equanimity in the face of dualities is a quality of a true devotee',
    strength: 7,
  },
  {
    from: '6.5',
    to: '6.35',
    type: 'thematic',
    description: 'Both discuss the challenge and method of controlling the mind',
    strength: 9,
  },
  {
    from: '18.66',
    to: '9.22',
    type: 'conceptual',
    description: 'Complete surrender and exclusive devotion bring divine protection',
    strength: 10,
  },
  {
    from: '4.7',
    to: '18.66',
    type: 'thematic',
    description: 'Divine manifestation and grace for the protection of dharma',
    strength: 7,
  },
  {
    from: '2.62',
    to: '2.63',
    type: 'conceptual',
    description: 'Sequential steps in the downward spiral from desire to destruction',
    strength: 10,
  },
  {
    from: '2.62',
    to: '6.5',
    type: 'practical',
    description: "Understanding desire's dangers necessitates self-control through mind mastery",
    strength: 8,
  },
  {
    from: '3.27',
    to: '15.7',
    type: 'conceptual',
    description: "Both explain the soul's false identification and true nature",
    strength: 8,
  },
  {
    from: '7.14',
    to: '18.66',
    type: 'thematic',
    description: 'Surrender to the Divine transcends the illusory material energy',
    strength: 9,
  },
  {
    from: '4.38',
    to: '13.8',
    type: 'practical',
    description: 'Spiritual qualities lead to the attainment of purifying knowledge',
    strength: 7,
  },
  {
    from: '9.27',
    to: '18.66',
    type: 'practical',
    description: 'Offering all actions leads naturally to complete surrender',
    strength: 8,
  },
  {
    from: '3.19',
    to: '5.10',
    type: 'thematic',
    description: 'Both describe the lotus-like purity of detached action',
    strength: 8,
  },
  {
    from: '12.13',
    to: '13.8',
    type: 'conceptual',
    description: 'Both enumerate essential spiritual qualities for seekers',
    strength: 9,
  },
  {
    from: '6.35',
    to: '2.14',
    type: 'practical',
    description: 'Practice and detachment help tolerate sensory disturbances',
    strength: 7,
  },
  {
    from: '2.47',
    to: '9.27',
    type: 'conceptual',
    description: 'Detached action evolves into offering all actions to the Divine',
    strength: 8,
  },
  {
    from: '9.22',
    to: '12.13',
    type: 'thematic',
    description: 'Divine care and devotee qualities are interconnected',
    strength: 7,
  },
  {
    from: '5.10',
    to: '9.27',
    type: 'practical',
    description: 'Surrendering results naturally leads to offering all actions',
    strength: 8,
  },
  {
    from: '1.47',
    to: '2.14',
    type: 'thematic',
    description: 'From despair to understanding the nature of dualities and suffering',
    strength: 8,
  },
  {
    from: '2.20',
    to: '2.56',
    type: 'conceptual',
    description: 'Understanding the eternal soul leads to steady wisdom and equanimity',
    strength: 9,
  },
  {
    from: '2.56',
    to: '12.13',
    type: 'practical',
    description: 'Qualities of steady wisdom are embodied in a true devotee',
    strength: 8,
  },
  {
    from: '3.5',
    to: '2.47',
    type: 'thematic',
    description: 'Action is inevitable, but we must act without attachment',
    strength: 8,
  },
  {
    from: '3.35',
    to: '18.46',
    type: 'conceptual',
    description: 'Following one\'s own dharma is the path to worshiping the divine',
    strength: 9,
  },
  {
    from: '4.18',
    to: '4.38',
    type: 'thematic',
    description: 'Wisdom in understanding action leads to purifying knowledge',
    strength: 8,
  },
  {
    from: '5.18',
    to: '6.5',
    type: 'practical',
    description: 'Equal vision comes from elevating oneself through self-mastery',
    strength: 7,
  },
  {
    from: '6.17',
    to: '6.35',
    type: 'thematic',
    description: 'Balance in life supports the practice of controlling the mind',
    strength: 8,
  },
  {
    from: '7.7',
    to: '10.20',
    type: 'conceptual',
    description: 'Everything rests on the divine, which is present in all beings',
    strength: 9,
  },
  {
    from: '8.5',
    to: '18.66',
    type: 'practical',
    description: 'Remembering the divine at death through complete surrender',
    strength: 8,
  },
  {
    from: '11.54',
    to: '9.22',
    type: 'thematic',
    description: 'Exclusive devotion enables divine vision and divine care',
    strength: 9,
  },
  {
    from: '12.8',
    to: '12.13',
    type: 'conceptual',
    description: 'Single-pointed focus on the divine manifests as devotional qualities',
    strength: 8,
  },
  {
    from: '14.22',
    to: '2.56',
    type: 'thematic',
    description: 'Transcending the modes of nature results in steady wisdom',
    strength: 8,
  },
  {
    from: '16.1',
    to: '13.8',
    type: 'conceptual',
    description: 'Both verses enumerate spiritual qualities necessary for seekers',
    strength: 9,
  },
  {
    from: '17.3',
    to: '3.27',
    type: 'practical',
    description: 'One\'s faith and nature determine how one identifies and acts',
    strength: 7,
  },
  {
    from: '18.78',
    to: '4.7',
    type: 'thematic',
    description: 'Where the divine is present, righteousness and victory prevail',
    strength: 8,
  },
  {
    from: '1.1',
    to: '1.47',
    type: 'conceptual',
    description: 'The beginning of the Gita leads to Arjuna\'s moral crisis',
    strength: 10,
  },
  {
    from: '2.20',
    to: '15.7',
    type: 'thematic',
    description: 'The eternal nature of the soul and its divine origin',
    strength: 9,
  },
  {
    from: '3.35',
    to: '2.47',
    type: 'practical',
    description: 'Following one\'s duty is essential for selfless action',
    strength: 8,
  },
  {
    from: '7.14',
    to: '7.7',
    type: 'conceptual',
    description: 'Maya covers the supreme reality that pervades everything',
    strength: 8,
  },
  {
    from: '10.20',
    to: '15.7',
    type: 'thematic',
    description: 'The divine Self present in all beings connects to the eternal soul',
    strength: 9,
  },
  {
    from: '4.7',
    to: '11.54',
    type: 'practical',
    description: 'Divine manifestation is realized through exclusive devotion',
    strength: 7,
  },
  // Additional connections for richer network
  {
    from: '2.14',
    to: '2.56',
    type: 'thematic',
    description: 'Tolerance of dualities leads to steady wisdom and equanimity',
    strength: 9,
  },
  {
    from: '2.56',
    to: '14.22',
    type: 'conceptual',
    description: 'Steady wisdom manifests as transcendence of the modes of nature',
    strength: 8,
  },
  {
    from: '3.5',
    to: '3.19',
    type: 'thematic',
    description: 'Since action is inevitable, one must act with detachment',
    strength: 8,
  },
  {
    from: '3.5',
    to: '3.35',
    type: 'practical',
    description: 'Compelled to act, one should follow their own dharma',
    strength: 7,
  },
  {
    from: '3.27',
    to: '2.20',
    type: 'conceptual',
    description: 'False ego identification vs understanding the eternal soul',
    strength: 8,
  },
  {
    from: '6.5',
    to: '12.8',
    type: 'practical',
    description: 'Self-mastery through mind control leads to single-pointed devotion',
    strength: 7,
  },
  {
    from: '6.17',
    to: '6.5',
    type: 'thematic',
    description: 'Balanced living supports the practice of self-elevation',
    strength: 8,
  },
  {
    from: '6.35',
    to: '12.8',
    type: 'conceptual',
    description: 'Controlling the restless mind through concentration on the divine',
    strength: 8,
  },
  {
    from: '7.14',
    to: '9.22',
    type: 'practical',
    description: 'Surrender transcends maya and invokes divine protection',
    strength: 9,
  },
  {
    from: '9.27',
    to: '2.47',
    type: 'thematic',
    description: 'Offering all actions is the ultimate expression of detached duty',
    strength: 8,
  },
  {
    from: '9.27',
    to: '12.8',
    type: 'practical',
    description: 'Dedicating all to the divine creates single-pointed focus',
    strength: 8,
  },
  {
    from: '11.54',
    to: '12.13',
    type: 'conceptual',
    description: 'Devotion leads to divine realization and devotional qualities',
    strength: 8,
  },
  {
    from: '12.8',
    to: '18.66',
    type: 'thematic',
    description: 'Single-pointed focus naturally culminates in complete surrender',
    strength: 9,
  },
  {
    from: '12.13',
    to: '16.1',
    type: 'conceptual',
    description: 'Devotional qualities align with divine virtues',
    strength: 8,
  },
  {
    from: '13.8',
    to: '16.1',
    type: 'thematic',
    description: 'Spiritual qualities and divine virtues complement each other',
    strength: 9,
  },
  {
    from: '15.7',
    to: '3.27',
    type: 'practical',
    description: 'Understanding the eternal soul helps overcome false identification',
    strength: 8,
  },
  {
    from: '16.1',
    to: '12.13',
    type: 'practical',
    description: 'Divine qualities manifest in the character of a true devotee',
    strength: 7,
  },
  {
    from: '17.3',
    to: '16.1',
    type: 'conceptual',
    description: 'Faith shapes character, character determines divine qualities',
    strength: 7,
  },
  {
    from: '18.46',
    to: '3.19',
    type: 'thematic',
    description: 'Worship through work is the path of detached action',
    strength: 8,
  },
  {
    from: '18.46',
    to: '9.27',
    type: 'practical',
    description: 'Natural occupation becomes worship when offered to the divine',
    strength: 9,
  },
  {
    from: '18.66',
    to: '12.8',
    type: 'conceptual',
    description: 'Complete surrender and single-pointed focus are one',
    strength: 9,
  },
  {
    from: '18.78',
    to: '18.66',
    type: 'thematic',
    description: 'Surrender to Krishna brings ultimate victory and righteousness',
    strength: 8,
  },
  {
    from: '2.62',
    to: '12.13',
    type: 'practical',
    description: 'Understanding desire\'s dangers cultivates detachment and compassion',
    strength: 7,
  },
  {
    from: '2.62',
    to: '6.35',
    type: 'thematic',
    description: 'The mind dwelling on objects must be controlled through practice',
    strength: 8,
  },
  {
    from: '2.63',
    to: '6.5',
    type: 'conceptual',
    description: 'Anger leads to destruction; self-elevation prevents the downfall',
    strength: 8,
  },
  {
    from: '3.19',
    to: '18.46',
    type: 'practical',
    description: 'Detached duty evolves into worship through work',
    strength: 8,
  },
  {
    from: '3.35',
    to: '1.47',
    type: 'thematic',
    description: 'From crisis to clarity about one\'s own dharma',
    strength: 7,
  },
  {
    from: '4.18',
    to: '3.5',
    type: 'conceptual',
    description: 'Understanding action/inaction while recognizing action is inevitable',
    strength: 8,
  },
  {
    from: '4.38',
    to: '2.20',
    type: 'thematic',
    description: 'Knowledge purifies and reveals the eternal nature of the soul',
    strength: 8,
  },
  {
    from: '5.10',
    to: '18.46',
    type: 'conceptual',
    description: 'Detached action for the divine becomes worship through work',
    strength: 8,
  },
  {
    from: '5.18',
    to: '12.13',
    type: 'practical',
    description: 'Equal vision manifests in compassion for all beings',
    strength: 8,
  },
  {
    from: '5.18',
    to: '2.56',
    type: 'thematic',
    description: 'Equal vision and steady wisdom both transcend dualities',
    strength: 8,
  },
  {
    from: '6.17',
    to: '2.14',
    type: 'practical',
    description: 'Balance in life helps tolerate sensory dualities',
    strength: 7,
  },
  {
    from: '7.7',
    to: '15.7',
    type: 'thematic',
    description: 'The supreme reality and the eternal soul are one',
    strength: 9,
  },
  {
    from: '8.5',
    to: '12.8',
    type: 'practical',
    description: 'Remembering the divine at death requires constant practice of focus',
    strength: 8,
  },
  {
    from: '9.22',
    to: '8.5',
    type: 'conceptual',
    description: 'Divine care ensures the devoted reach the divine',
    strength: 8,
  },
  {
    from: '10.20',
    to: '7.7',
    type: 'conceptual',
    description: 'The divine Self in all hearts is the supreme reality pervading all',
    strength: 9,
  },
  {
    from: '11.54',
    to: '18.66',
    type: 'thematic',
    description: 'Exclusive devotion and complete surrender reveal the divine',
    strength: 9,
  },
  {
    from: '14.22',
    to: '12.13',
    type: 'practical',
    description: 'Transcending modes manifests as devotional equanimity',
    strength: 7,
  },
  {
    from: '1.47',
    to: '18.66',
    type: 'conceptual',
    description: 'From despair and confusion to ultimate surrender and liberation',
    strength: 8,
  },
  {
    from: '2.14',
    to: '5.18',
    type: 'thematic',
    description: 'Tolerance of dualities leads to seeing all with equal vision',
    strength: 7,
  },
  {
    from: '2.20',
    to: '13.8',
    type: 'practical',
    description: 'Knowledge of the eternal soul cultivates spiritual qualities',
    strength: 7,
  },
  {
    from: '2.47',
    to: '3.35',
    type: 'conceptual',
    description: 'Selfless action means following one\'s own duty',
    strength: 8,
  },
  {
    from: '2.47',
    to: '4.18',
    type: 'thematic',
    description: 'Detached action requires wisdom in understanding action',
    strength: 8,
  },
  {
    from: '2.56',
    to: '6.35',
    type: 'practical',
    description: 'Steady wisdom requires controlling the restless mind',
    strength: 8,
  },
  {
    from: '3.5',
    to: '18.46',
    type: 'thematic',
    description: 'Inevitable action should be performed as worship',
    strength: 7,
  },
  {
    from: '3.19',
    to: '4.18',
    type: 'conceptual',
    description: 'Detached action requires wisdom to see action in inaction',
    strength: 8,
  },
  {
    from: '3.27',
    to: '13.8',
    type: 'practical',
    description: 'Overcoming false ego requires developing spiritual qualities',
    strength: 7,
  },
  {
    from: '3.35',
    to: '17.3',
    type: 'thematic',
    description: 'One\'s dharma aligns with one\'s faith and nature',
    strength: 8,
  },
  {
    from: '4.7',
    to: '1.1',
    type: 'conceptual',
    description: 'The battlefield crisis invokes divine intervention',
    strength: 7,
  },
  {
    from: '4.38',
    to: '16.1',
    type: 'thematic',
    description: 'Knowledge purifies and manifests as divine qualities',
    strength: 8,
  },
  {
    from: '5.10',
    to: '3.35',
    type: 'practical',
    description: 'Detached action means performing one\'s own duty',
    strength: 7,
  },
  {
    from: '6.5',
    to: '13.8',
    type: 'conceptual',
    description: 'Self-mastery is achieved through spiritual qualities',
    strength: 7,
  },
  {
    from: '6.35',
    to: '6.17',
    type: 'thematic',
    description: 'Mind control requires both practice and balanced living',
    strength: 9,
  },
  {
    from: '7.14',
    to: '11.54',
    type: 'practical',
    description: 'Surrender transcends maya and enables divine vision',
    strength: 8,
  },
  {
    from: '9.22',
    to: '18.66',
    type: 'thematic',
    description: 'Exclusive devotion invokes complete divine care and liberation',
    strength: 9,
  },
  {
    from: '9.27',
    to: '11.54',
    type: 'conceptual',
    description: 'Offering all actions is the practice of exclusive devotion',
    strength: 8,
  },
  {
    from: '10.20',
    to: '2.20',
    type: 'thematic',
    description: 'The divine Self and the eternal soul are one reality',
    strength: 9,
  },
  {
    from: '12.13',
    to: '2.14',
    type: 'conceptual',
    description: 'Devotional equanimity enables tolerance of dualities',
    strength: 8,
  },
  {
    from: '15.7',
    to: '7.14',
    type: 'practical',
    description: 'Understanding the eternal soul helps transcend maya',
    strength: 8,
  },
  {
    from: '18.46',
    to: '18.66',
    type: 'thematic',
    description: 'Worship through duty leads to complete surrender',
    strength: 8,
  },
  {
    from: '18.78',
    to: '1.1',
    type: 'conceptual',
    description: 'The beginning and end: battlefield crisis to divine victory',
    strength: 9,
  },
  {
    from: '2.47',
    to: '6.35',
    type: 'practical',
    description: 'Detached action requires controlling the restless mind',
    strength: 7,
  },
  {
    from: '2.56',
    to: '5.18',
    type: 'thematic',
    description: 'Steady wisdom and equal vision both transcend appearances',
    strength: 8,
  },
  {
    from: '3.19',
    to: '12.13',
    type: 'conceptual',
    description: 'Detached action cultivates devotional qualities',
    strength: 7,
  },
  {
    from: '4.7',
    to: '7.14',
    type: 'thematic',
    description: 'Divine intervention overcomes the power of maya',
    strength: 7,
  },
  {
    from: '4.38',
    to: '15.7',
    type: 'practical',
    description: 'Knowledge reveals the eternal divine nature of the soul',
    strength: 8,
  },
  {
    from: '6.5',
    to: '2.63',
    type: 'thematic',
    description: 'Self-mastery prevents the path to self-destruction',
    strength: 8,
  },
  {
    from: '7.7',
    to: '18.66',
    type: 'conceptual',
    description: 'Surrendering to the supreme reality that pervades all',
    strength: 8,
  },
  {
    from: '9.22',
    to: '11.54',
    type: 'practical',
    description: 'Exclusive devotion brings divine care and divine vision',
    strength: 9,
  },
  {
    from: '12.8',
    to: '8.5',
    type: 'thematic',
    description: 'Constant focus on the divine ensures remembrance at death',
    strength: 8,
  },
  {
    from: '13.8',
    to: '2.56',
    type: 'conceptual',
    description: 'Spiritual qualities manifest as steady wisdom',
    strength: 8,
  },
  {
    from: '16.1',
    to: '2.56',
    type: 'practical',
    description: 'Divine qualities lead to steady wisdom',
    strength: 7,
  },
  {
    from: '18.46',
    to: '5.10',
    type: 'thematic',
    description: 'Work as worship is detached action for the divine',
    strength: 9,
  },
];
