import type { VerseCuration } from '../types.js';

// GENERATED by scripts/generate-concepts-jev.ts (TypeSafe jev-1.13.0, threshold 0.8) — do not edit by hand.
//
// Machine-proposed concepts and placeholder themes for verses that have no
// entry in curation.ts. Every entry is reviewed: false. To accept one, move
// it into curation.ts (which always wins), give it a real theme, and drop
// the flag; to correct it, do the same with the corrected concepts. Rerunning
// the script regenerates only what curation.ts does not cover.
export const generatedCuration: Record<string, VerseCuration> = {
  '1.2': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'guru'],
    reviewed: false,
  },
  '1.3': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.4': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.5': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.6': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.7': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.8': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.9': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief', 'death'],
    reviewed: false,
  },
  '1.10': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.11': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'duty'],
    reviewed: false,
  },
  '1.12': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.13': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.14': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.15': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.16': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.17': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.18': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.19': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.20': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.21': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.22': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.23': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.24': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.25': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '1.26': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief', 'attachment'],
    reviewed: false,
  },
  '1.27': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'compassion', 'war'],
    reviewed: false,
  },
  '1.28': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'war', 'attachment'],
    reviewed: false,
  },
  '1.29': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'war', 'attachment'],
    reviewed: false,
  },
  '1.30': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'war'],
    reviewed: false,
  },
  '1.31': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'illusion', 'war'],
    reviewed: false,
  },
  '1.32': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief', 'death'],
    reviewed: false,
  },
  '1.33': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief', 'death', 'compassion'],
    reviewed: false,
  },
  '1.34': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief', 'compassion', 'death'],
    reviewed: false,
  },
  '1.35': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief', 'death', 'compassion'],
    reviewed: false,
  },
  '1.36': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief', 'death', 'compassion'],
    reviewed: false,
  },
  '1.37': {
    theme: 'Soul and self',
    concepts: ['death', 'compassion', 'grief'],
    reviewed: false,
  },
  '1.38': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'dharma', 'death'],
    reviewed: false,
  },
  '1.39': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'dharma', 'death'],
    reviewed: false,
  },
  '1.40': {
    theme: 'Duty and action',
    concepts: ['dharma', 'grief'],
    reviewed: false,
  },
  '1.41': {
    theme: 'Duty and action',
    concepts: ['dharma', 'purity'],
    reviewed: false,
  },
  '1.42': {
    theme: 'Duty and action',
    concepts: ['dharma', 'sacrifice', 'death'],
    reviewed: false,
  },
  '1.43': {
    theme: 'Duty and action',
    concepts: ['dharma', 'purity'],
    reviewed: false,
  },
  '1.44': {
    theme: 'Duty and action',
    concepts: ['dharma', 'grief'],
    reviewed: false,
  },
  '1.45': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'death', 'dharma'],
    reviewed: false,
  },
  '1.46': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'death', 'grief'],
    reviewed: false,
  },
  '2.1': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'war'],
    reviewed: false,
  },
  '2.2': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'purity', 'knowledge'],
    reviewed: false,
  },
  '2.3': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'renunciation', 'discipline'],
    reviewed: false,
  },
  '2.4': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief', 'compassion'],
    reviewed: false,
  },
  '2.5': {
    theme: 'Faith and character',
    concepts: ['compassion', 'death', 'dharma'],
    reviewed: false,
  },
  '2.6': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'grief', 'death'],
    reviewed: false,
  },
  '2.7': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'guru', 'duty'],
    reviewed: false,
  },
  '2.8': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'attachment'],
    reviewed: false,
  },
  '2.9': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'renunciation', 'grief'],
    reviewed: false,
  },
  '2.10': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'war'],
    reviewed: false,
  },
  '2.11': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'knowledge', 'soul'],
    reviewed: false,
  },
  '2.12': {
    theme: 'Soul and self',
    concepts: ['soul', 'knowledge', 'death'],
    reviewed: false,
  },
  '2.13': {
    theme: 'Soul and self',
    concepts: ['soul', 'impermanence', 'death', 'knowledge'],
    reviewed: false,
  },
  '2.15': {
    theme: 'Final liberation',
    concepts: ['equanimity', 'transcendence', 'liberation'],
    reviewed: false,
  },
  '2.16': {
    theme: 'Soul and self',
    concepts: ['soul', 'impermanence', 'knowledge'],
    reviewed: false,
  },
  '2.17': {
    theme: 'Soul and self',
    concepts: ['soul', 'knowledge', 'death'],
    reviewed: false,
  },
  '2.18': {
    theme: 'Soul and self',
    concepts: ['soul', 'impermanence', 'knowledge'],
    reviewed: false,
  },
  '2.19': {
    theme: 'Soul and self',
    concepts: ['soul', 'knowledge', 'death'],
    reviewed: false,
  },
  '2.21': {
    theme: 'Soul and self',
    concepts: ['soul', 'knowledge', 'death'],
    reviewed: false,
  },
  '2.22': {
    theme: 'Soul and self',
    concepts: ['soul', 'impermanence', 'death'],
    reviewed: false,
  },
  '2.23': {
    theme: 'Soul and self',
    concepts: ['soul', 'knowledge', 'death'],
    reviewed: false,
  },
  '2.24': {
    theme: 'Knowledge and realization',
    concepts: ['soul', 'knowledge', 'self-realization'],
    reviewed: false,
  },
  '2.25': {
    theme: 'Soul and self',
    concepts: ['soul', 'knowledge', 'grief'],
    reviewed: false,
  },
  '2.26': {
    theme: 'Soul and self',
    concepts: ['soul', 'grief', 'death'],
    reviewed: false,
  },
  '2.27': {
    theme: 'Soul and self',
    concepts: ['death', 'grief', 'impermanence'],
    reviewed: false,
  },
  '2.28': {
    theme: 'Soul and self',
    concepts: ['impermanence', 'knowledge', 'death'],
    reviewed: false,
  },
  '2.29': {
    theme: 'Knowledge and realization',
    concepts: ['soul', 'knowledge', 'self-realization'],
    reviewed: false,
  },
  '2.30': {
    theme: 'Soul and self',
    concepts: ['soul', 'grief', 'death', 'knowledge'],
    reviewed: false,
  },
  '2.31': {
    theme: 'Duty and action',
    concepts: ['duty', 'dharma', 'war'],
    reviewed: false,
  },
  '2.32': {
    theme: 'Duty and action',
    concepts: ['war', 'duty', 'action'],
    reviewed: false,
  },
  '2.33': {
    theme: 'Duty and action',
    concepts: ['duty', 'dharma', 'war', 'action'],
    reviewed: false,
  },
  '2.34': {
    theme: 'Duty and action',
    concepts: ['dharma', 'duty'],
    reviewed: false,
  },
  '2.35': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'duty', 'grief'],
    reviewed: false,
  },
  '2.36': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['grief', 'equanimity'],
    reviewed: false,
  },
  '2.37': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'death', 'action'],
    reviewed: false,
  },
  '2.38': {
    theme: 'Duty and action',
    concepts: ['equanimity', 'detachment', 'action', 'karma-yoga'],
    reviewed: false,
  },
  '2.39': {
    theme: 'Duty and action',
    concepts: ['karma-yoga', 'action', 'detachment', 'bondage'],
    reviewed: false,
  },
  '2.40': {
    theme: 'Duty and action',
    concepts: ['dharma', 'self-realization', 'action'],
    reviewed: false,
  },
  '2.41': {
    theme: 'Knowledge and realization',
    concepts: ['wisdom', 'knowledge', 'devotion'],
    reviewed: false,
  },
  '2.42': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'attachment', 'knowledge'],
    reviewed: false,
  },
  '2.43': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'attachment', 'knowledge'],
    reviewed: false,
  },
  '2.44': {
    theme: 'Meditation and mind',
    concepts: ['attachment', 'devotion', 'desire'],
    reviewed: false,
  },
  '2.45': {
    theme: 'Final liberation',
    concepts: ['transcendence', 'modes-of-nature', 'equanimity'],
    reviewed: false,
  },
  '2.46': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'self-realization', 'wisdom'],
    reviewed: false,
  },
  '2.48': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'detachment', 'karma-yoga', 'attachment'],
    reviewed: false,
  },
  '2.49': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'devotion', 'detachment'],
    reviewed: false,
  },
  '2.50': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'action', 'transcendence'],
    reviewed: false,
  },
  '2.51': {
    theme: 'Final liberation',
    concepts: ['liberation', 'devotion', 'detachment', 'bondage'],
    reviewed: false,
  },
  '2.52': {
    theme: 'Knowledge and realization',
    concepts: ['illusion', 'wisdom', 'knowledge'],
    reviewed: false,
  },
  '2.53': {
    theme: 'Knowledge and realization',
    concepts: ['self-realization', 'wisdom', 'transcendence'],
    reviewed: false,
  },
  '2.54': {
    theme: 'Knowledge and realization',
    concepts: ['wisdom', 'self-realization', 'transcendence'],
    reviewed: false,
  },
  '2.55': {
    theme: 'Knowledge and realization',
    concepts: ['desire', 'renunciation', 'self-realization', 'wisdom'],
    reviewed: false,
  },
  '2.57': {
    theme: 'Knowledge and realization',
    concepts: ['equanimity', 'knowledge', 'wisdom', 'detachment'],
    reviewed: false,
  },
  '2.58': {
    theme: 'Knowledge and realization',
    concepts: ['discipline', 'wisdom', 'self-realization'],
    reviewed: false,
  },
  '2.59': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'renunciation', 'attachment'],
    reviewed: false,
  },
  '2.60': {
    theme: 'Knowledge and realization',
    concepts: ['discipline', 'wisdom', 'knowledge'],
    reviewed: false,
  },
  '2.61': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'wisdom', 'meditation'],
    reviewed: false,
  },
  '2.64': {
    theme: 'Meditation and mind',
    concepts: ['attachment', 'discipline', 'detachment'],
    reviewed: false,
  },
  '2.65': {
    theme: 'Knowledge and realization',
    concepts: ['wisdom', 'devotion', 'transcendence'],
    reviewed: false,
  },
  '2.66': {
    theme: 'Knowledge and realization',
    concepts: ['wisdom', 'devotion', 'equanimity'],
    reviewed: false,
  },
  '2.67': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'wisdom', 'attachment'],
    reviewed: false,
  },
  '2.68': {
    theme: 'Knowledge and realization',
    concepts: ['discipline', 'wisdom', 'knowledge'],
    reviewed: false,
  },
  '2.69': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'self-realization', 'transcendence'],
    reviewed: false,
  },
  '2.70': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'equanimity', 'discipline'],
    reviewed: false,
  },
  '2.71': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'renunciation', 'ego'],
    reviewed: false,
  },
  '2.72': {
    theme: 'Final liberation',
    concepts: ['liberation', 'death', 'self-realization'],
    reviewed: false,
  },
  '3.1': {
    theme: 'Duty and action',
    concepts: ['action', 'war', 'karma-yoga'],
    reviewed: false,
  },
  '3.2': {
    theme: 'Knowledge and realization',
    concepts: ['illusion', 'action', 'wisdom'],
    reviewed: false,
  },
  '3.3': {
    theme: 'Knowledge and realization',
    concepts: ['devotion', 'self-realization', 'knowledge'],
    reviewed: false,
  },
  '3.4': {
    theme: 'Duty and action',
    concepts: ['action', 'renunciation', 'karma-yoga'],
    reviewed: false,
  },
  '3.6': {
    theme: 'Meditation and mind',
    concepts: ['action', 'discipline', 'attachment'],
    reviewed: false,
  },
  '3.7': {
    theme: 'Duty and action',
    concepts: ['karma-yoga', 'action', 'detachment', 'attachment'],
    reviewed: false,
  },
  '3.8': {
    theme: 'Duty and action',
    concepts: ['action', 'duty', 'karma-yoga'],
    reviewed: false,
  },
  '3.9': {
    theme: 'Duty and action',
    concepts: ['action', 'sacrifice', 'bondage', 'karma-yoga'],
    reviewed: false,
  },
  '3.10': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'action', 'liberation'],
    reviewed: false,
  },
  '3.11': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'action', 'karma-yoga'],
    reviewed: false,
  },
  '3.12': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'action', 'dharma'],
    reviewed: false,
  },
  '3.13': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'devotion', 'purity'],
    reviewed: false,
  },
  '3.14': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'action', 'duty'],
    reviewed: false,
  },
  '3.15': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'action', 'supreme-person'],
    reviewed: false,
  },
  '3.16': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'action', 'dharma'],
    reviewed: false,
  },
  '3.17': {
    theme: 'Duty and action',
    concepts: ['self-realization', 'action', 'duty'],
    reviewed: false,
  },
  '3.18': {
    theme: 'Duty and action',
    concepts: ['action', 'duty', 'self-realization', 'karma-yoga'],
    reviewed: false,
  },
  '3.20': {
    theme: 'Duty and action',
    concepts: ['action', 'duty', 'karma-yoga'],
    reviewed: false,
  },
  '3.21': {
    theme: 'Duty and action',
    concepts: ['action', 'karma-yoga', 'dharma'],
    reviewed: false,
  },
  '3.22': {
    theme: 'Duty and action',
    concepts: ['action', 'karma-yoga', 'duty'],
    reviewed: false,
  },
  '3.23': {
    theme: 'Duty and action',
    concepts: ['action', 'duty', 'karma-yoga'],
    reviewed: false,
  },
  '3.24': {
    theme: 'Duty and action',
    concepts: ['action', 'duty', 'dharma'],
    reviewed: false,
  },
  '3.25': {
    theme: 'Duty and action',
    concepts: ['detachment', 'action', 'attachment', 'karma-yoga'],
    reviewed: false,
  },
  '3.26': {
    theme: 'Duty and action',
    concepts: ['action', 'karma-yoga', 'attachment'],
    reviewed: false,
  },
  '3.28': {
    theme: 'Duty and action',
    concepts: ['knowledge', 'action', 'attachment', 'detachment'],
    reviewed: false,
  },
  '3.29': {
    theme: 'Knowledge and realization',
    concepts: ['action', 'modes-of-nature', 'illusion', 'knowledge'],
    reviewed: false,
  },
  '3.30': {
    theme: 'Duty and action',
    concepts: ['action', 'karma-yoga', 'surrender', 'detachment'],
    reviewed: false,
  },
  '3.31': {
    theme: 'Duty and action',
    concepts: ['action', 'liberation', 'karma-yoga', 'bondage'],
    reviewed: false,
  },
  '3.32': {
    theme: 'Knowledge and realization',
    concepts: ['action', 'illusion', 'knowledge'],
    reviewed: false,
  },
  '3.33': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'action', 'bondage'],
    reviewed: false,
  },
  '3.34': {
    theme: 'Meditation and mind',
    concepts: ['attachment', 'discipline', 'self-realization'],
    reviewed: false,
  },
  '3.36': {
    theme: 'Duty and action',
    concepts: ['action', 'desire', 'bondage'],
    reviewed: false,
  },
  '3.37': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'anger', 'modes-of-nature'],
    reviewed: false,
  },
  '3.38': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'bondage'],
    reviewed: false,
  },
  '3.39': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'knowledge', 'bondage'],
    reviewed: false,
  },
  '3.40': {
    theme: 'Knowledge and realization',
    concepts: ['desire', 'knowledge', 'illusion'],
    reviewed: false,
  },
  '3.41': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'discipline', 'self-realization'],
    reviewed: false,
  },
  '3.42': {
    theme: 'Soul and self',
    concepts: ['soul', 'wisdom', 'transcendence'],
    reviewed: false,
  },
  '3.43': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'discipline', 'wisdom'],
    reviewed: false,
  },
  '4.1': {
    theme: 'Knowledge and realization',
    concepts: ['guru', 'knowledge', 'supreme-person'],
    reviewed: false,
  },
  '4.2': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'guru'],
    reviewed: false,
  },
  '4.3': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'devotion', 'supreme-person'],
    reviewed: false,
  },
  '4.4': {
    theme: 'Knowledge and realization',
    concepts: ['guru', 'knowledge'],
    reviewed: false,
  },
  '4.5': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'soul', 'supreme-person'],
    reviewed: false,
  },
  '4.6': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'transcendence', 'soul'],
    reviewed: false,
  },
  '4.8': {
    theme: 'Duty and action',
    concepts: ['dharma', 'grace', 'supreme-person'],
    reviewed: false,
  },
  '4.9': {
    theme: 'Final liberation',
    concepts: ['liberation', 'knowledge', 'death'],
    reviewed: false,
  },
  '4.10': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'devotion', 'knowledge', 'attachment'],
    reviewed: false,
  },
  '4.11': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'devotion', 'grace'],
    reviewed: false,
  },
  '4.12': {
    theme: 'Duty and action',
    concepts: ['action', 'desire', 'sacrifice'],
    reviewed: false,
  },
  '4.13': {
    theme: 'Duty and action',
    concepts: ['action', 'modes-of-nature', 'supreme-person'],
    reviewed: false,
  },
  '4.14': {
    theme: 'Duty and action',
    concepts: ['action', 'detachment', 'knowledge', 'bondage'],
    reviewed: false,
  },
  '4.15': {
    theme: 'Duty and action',
    concepts: ['action', 'duty', 'knowledge'],
    reviewed: false,
  },
  '4.16': {
    theme: 'Duty and action',
    concepts: ['action', 'knowledge', 'liberation'],
    reviewed: false,
  },
  '4.17': {
    theme: 'Knowledge and realization',
    concepts: ['action', 'knowledge', 'wisdom'],
    reviewed: false,
  },
  '4.19': {
    theme: 'Duty and action',
    concepts: ['action', 'knowledge', 'desire', 'karma-yoga'],
    reviewed: false,
  },
  '4.20': {
    theme: 'Duty and action',
    concepts: ['detachment', 'action', 'renunciation', 'attachment'],
    reviewed: false,
  },
  '4.21': {
    theme: 'Duty and action',
    concepts: ['action', 'detachment', 'karma-yoga', 'renunciation'],
    reviewed: false,
  },
  '4.22': {
    theme: 'Duty and action',
    concepts: ['equanimity', 'detachment', 'action', 'transcendence'],
    reviewed: false,
  },
  '4.23': {
    theme: 'Duty and action',
    concepts: ['action', 'transcendence', 'knowledge', 'detachment'],
    reviewed: false,
  },
  '4.24': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'action', 'liberation'],
    reviewed: false,
  },
  '4.25': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'action'],
    reviewed: false,
  },
  '4.26': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'discipline', 'renunciation'],
    reviewed: false,
  },
  '4.27': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'self-realization', 'sacrifice'],
    reviewed: false,
  },
  '4.28': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'austerity', 'knowledge'],
    reviewed: false,
  },
  '4.29': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'discipline', 'action'],
    reviewed: false,
  },
  '4.30': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'liberation', 'action'],
    reviewed: false,
  },
  '4.31': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'action', 'karma-yoga'],
    reviewed: false,
  },
  '4.32': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'action', 'liberation', 'knowledge'],
    reviewed: false,
  },
  '4.33': {
    theme: 'Duty and action',
    concepts: ['knowledge', 'sacrifice', 'action'],
    reviewed: false,
  },
  '4.34': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'guru', 'self-realization'],
    reviewed: false,
  },
  '4.35': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'unity', 'illusion', 'supreme-person'],
    reviewed: false,
  },
  '4.36': {
    theme: 'Final liberation',
    concepts: ['knowledge', 'liberation', 'transcendence'],
    reviewed: false,
  },
  '4.37': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'action', 'bondage'],
    reviewed: false,
  },
  '4.39': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'faith', 'discipline'],
    reviewed: false,
  },
  '4.40': {
    theme: 'Faith and character',
    concepts: ['faith', 'knowledge', 'liberation'],
    reviewed: false,
  },
  '4.41': {
    theme: 'Duty and action',
    concepts: ['action', 'detachment', 'renunciation', 'karma-yoga'],
    reviewed: false,
  },
  '4.42': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'wisdom', 'illusion'],
    reviewed: false,
  },
  '5.1': {
    theme: 'Duty and action',
    concepts: ['action', 'renunciation', 'devotion'],
    reviewed: false,
  },
  '5.2': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'action', 'devotion', 'karma-yoga'],
    reviewed: false,
  },
  '5.3': {
    theme: 'Duty and action',
    concepts: ['detachment', 'renunciation', 'liberation', 'equanimity'],
    reviewed: false,
  },
  '5.4': {
    theme: 'Duty and action',
    concepts: ['karma-yoga', 'action', 'knowledge'],
    reviewed: false,
  },
  '5.5': {
    theme: 'Knowledge and realization',
    concepts: ['devotion', 'knowledge', 'self-realization'],
    reviewed: false,
  },
  '5.6': {
    theme: 'Duty and action',
    concepts: ['devotion', 'renunciation', 'action'],
    reviewed: false,
  },
  '5.7': {
    theme: 'Duty and action',
    concepts: ['action', 'karma-yoga', 'devotion', 'discipline'],
    reviewed: false,
  },
  '5.8': {
    theme: 'Duty and action',
    concepts: ['action', 'knowledge', 'detachment', 'renunciation'],
    reviewed: false,
  },
  '5.9': {
    theme: 'Duty and action',
    concepts: ['action', 'knowledge', 'detachment', 'self-realization'],
    reviewed: false,
  },
  '5.11': {
    theme: 'Duty and action',
    concepts: ['action', 'attachment', 'renunciation', 'detachment'],
    reviewed: false,
  },
  '5.12': {
    theme: 'Duty and action',
    concepts: ['detachment', 'karma-yoga', 'action', 'attachment'],
    reviewed: false,
  },
  '5.13': {
    theme: 'Duty and action',
    concepts: ['action', 'renunciation', 'discipline'],
    reviewed: false,
  },
  '5.14': {
    theme: 'Duty and action',
    concepts: ['action', 'modes-of-nature', 'ego'],
    reviewed: false,
  },
  '5.15': {
    theme: 'Knowledge and realization',
    concepts: ['illusion', 'knowledge', 'action'],
    reviewed: false,
  },
  '5.16': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'self-realization', 'illusion'],
    reviewed: false,
  },
  '5.17': {
    theme: 'Final liberation',
    concepts: ['liberation', 'surrender', 'knowledge'],
    reviewed: false,
  },
  '5.19': {
    theme: 'Final liberation',
    concepts: ['equanimity', 'liberation', 'transcendence', 'self-realization'],
    reviewed: false,
  },
  '5.20': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'transcendence', 'detachment', 'wisdom'],
    reviewed: false,
  },
  '5.21': {
    theme: 'Meditation and mind',
    concepts: ['self-realization', 'attachment', 'meditation'],
    reviewed: false,
  },
  '5.22': {
    theme: 'Soul and self',
    concepts: ['impermanence', 'wisdom', 'renunciation'],
    reviewed: false,
  },
  '5.23': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'discipline', 'anger'],
    reviewed: false,
  },
  '5.24': {
    theme: 'Final liberation',
    concepts: ['liberation', 'self-realization', 'transcendence'],
    reviewed: false,
  },
  '5.25': {
    theme: 'Final liberation',
    concepts: ['liberation', 'transcendence', 'action'],
    reviewed: false,
  },
  '5.26': {
    theme: 'Meditation and mind',
    concepts: ['liberation', 'self-realization', 'desire', 'discipline'],
    reviewed: false,
  },
  '5.27': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'liberation', 'meditation'],
    reviewed: false,
  },
  '5.28': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'liberation', 'meditation'],
    reviewed: false,
  },
  '5.29': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'supreme-person', 'knowledge'],
    reviewed: false,
  },
  '6.1': {
    theme: 'Duty and action',
    concepts: ['detachment', 'action', 'renunciation', 'karma-yoga'],
    reviewed: false,
  },
  '6.2': {
    theme: 'Meditation and mind',
    concepts: ['renunciation', 'desire', 'discipline'],
    reviewed: false,
  },
  '6.3': {
    theme: 'Duty and action',
    concepts: ['action', 'renunciation', 'discipline'],
    reviewed: false,
  },
  '6.4': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'desire', 'detachment'],
    reviewed: false,
  },
  '6.6': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'meditation'],
    reviewed: false,
  },
  '6.7': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'transcendence', 'discipline'],
    reviewed: false,
  },
  '6.8': {
    theme: 'Knowledge and realization',
    concepts: ['self-realization', 'equanimity', 'knowledge', 'transcendence'],
    reviewed: false,
  },
  '6.9': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'transcendence', 'wisdom'],
    reviewed: false,
  },
  '6.10': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'meditation', 'desire'],
    reviewed: false,
  },
  '6.11': {
    theme: 'Meditation and mind',
    concepts: ['meditation', 'discipline', 'purity'],
    reviewed: false,
  },
  '6.12': {
    theme: 'Meditation and mind',
    concepts: ['meditation', 'discipline', 'purity'],
    reviewed: false,
  },
  '6.13': {
    theme: 'Meditation and mind',
    concepts: ['meditation', 'discipline', 'devotion'],
    reviewed: false,
  },
  '6.14': {
    theme: 'Meditation and mind',
    concepts: ['meditation', 'discipline', 'devotion'],
    reviewed: false,
  },
  '6.15': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'liberation', 'meditation'],
    reviewed: false,
  },
  '6.16': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'meditation', 'austerity'],
    reviewed: false,
  },
  '6.18': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'desire', 'meditation'],
    reviewed: false,
  },
  '6.19': {
    theme: 'Meditation and mind',
    concepts: ['meditation', 'discipline', 'self-realization'],
    reviewed: false,
  },
  '6.20': {
    theme: 'Meditation and mind',
    concepts: ['self-realization', 'meditation', 'discipline', 'transcendence'],
    reviewed: false,
  },
  '6.21': {
    theme: 'Meditation and mind',
    concepts: ['self-realization', 'meditation', 'discipline', 'transcendence'],
    reviewed: false,
  },
  '6.22': {
    theme: 'Meditation and mind',
    concepts: ['self-realization', 'meditation', 'transcendence', 'discipline'],
    reviewed: false,
  },
  '6.23': {
    theme: 'Meditation and mind',
    concepts: ['self-realization', 'meditation', 'discipline', 'transcendence'],
    reviewed: false,
  },
  '6.24': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'desire', 'renunciation', 'meditation'],
    reviewed: false,
  },
  '6.25': {
    theme: 'Meditation and mind',
    concepts: ['meditation', 'discipline', 'self-realization'],
    reviewed: false,
  },
  '6.26': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'meditation', 'self-realization'],
    reviewed: false,
  },
  '6.27': {
    theme: 'Meditation and mind',
    concepts: ['meditation', 'transcendence', 'self-realization'],
    reviewed: false,
  },
  '6.28': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'meditation', 'self-realization'],
    reviewed: false,
  },
  '6.29': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['unity', 'self-realization', 'equanimity'],
    reviewed: false,
  },
  '6.30': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['unity', 'supreme-person', 'knowledge'],
    reviewed: false,
  },
  '6.31': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['devotion', 'unity', 'supreme-person'],
    reviewed: false,
  },
  '6.32': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'transcendence', 'self-realization'],
    reviewed: false,
  },
  '6.33': {
    theme: 'Meditation and mind',
    concepts: ['meditation', 'discipline'],
    reviewed: false,
  },
  '6.34': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'meditation'],
    reviewed: false,
  },
  '6.36': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'self-realization', 'meditation'],
    reviewed: false,
  },
  '6.37': {
    theme: 'Knowledge and realization',
    concepts: ['self-realization', 'faith', 'meditation'],
    reviewed: false,
  },
  '6.38': {
    theme: 'Final liberation',
    concepts: ['transcendence', 'meditation', 'illusion'],
    reviewed: false,
  },
  '6.39': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'faith', 'grace'],
    reviewed: false,
  },
  '6.40': {
    theme: 'Duty and action',
    concepts: ['dharma', 'action', 'transcendence'],
    reviewed: false,
  },
  '6.41': {
    theme: 'Knowledge and realization',
    concepts: ['self-realization', 'bondage', 'death'],
    reviewed: false,
  },
  '6.42': {
    theme: 'Meditation and mind',
    concepts: ['meditation', 'wisdom', 'discipline'],
    reviewed: false,
  },
  '6.43': {
    theme: 'Knowledge and realization',
    concepts: ['self-realization', 'discipline', 'soul'],
    reviewed: false,
  },
  '6.44': {
    theme: 'Meditation and mind',
    concepts: ['transcendence', 'meditation', 'discipline'],
    reviewed: false,
  },
  '6.45': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'liberation', 'self-realization'],
    reviewed: false,
  },
  '6.46': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'transcendence', 'meditation'],
    reviewed: false,
  },
  '6.47': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'faith', 'remembrance'],
    reviewed: false,
  },
  '7.1': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'devotion', 'meditation'],
    reviewed: false,
  },
  '7.2': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'self-realization', 'wisdom'],
    reviewed: false,
  },
  '7.3': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'self-realization', 'supreme-person'],
    reviewed: false,
  },
  '7.4': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'knowledge', 'ego'],
    reviewed: false,
  },
  '7.5': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'knowledge', 'soul'],
    reviewed: false,
  },
  '7.6': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'knowledge', 'unity'],
    reviewed: false,
  },
  '7.8': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '7.9': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'unity', 'supreme-person'],
    reviewed: false,
  },
  '7.10': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'knowledge', 'opulence'],
    reviewed: false,
  },
  '7.11': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['desire', 'opulence', 'supreme-person'],
    reviewed: false,
  },
  '7.12': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'transcendence', 'supreme-person'],
    reviewed: false,
  },
  '7.13': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'illusion', 'transcendence'],
    reviewed: false,
  },
  '7.15': {
    theme: 'Knowledge and realization',
    concepts: ['surrender', 'illusion', 'knowledge'],
    reviewed: false,
  },
  '7.16': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'knowledge', 'desire'],
    reviewed: false,
  },
  '7.17': {
    theme: 'Knowledge and realization',
    concepts: ['devotion', 'knowledge', 'wisdom'],
    reviewed: false,
  },
  '7.18': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'knowledge', 'liberation'],
    reviewed: false,
  },
  '7.19': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'knowledge', 'supreme-person'],
    reviewed: false,
  },
  '7.20': {
    theme: 'Knowledge and realization',
    concepts: ['desire', 'knowledge', 'illusion'],
    reviewed: false,
  },
  '7.21': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['faith', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '7.22': {
    theme: 'Faith and character',
    concepts: ['faith', 'supreme-person', 'desire'],
    reviewed: false,
  },
  '7.23': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'liberation', 'supreme-person'],
    reviewed: false,
  },
  '7.24': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'supreme-person', 'illusion'],
    reviewed: false,
  },
  '7.25': {
    theme: 'Knowledge and realization',
    concepts: ['illusion', 'knowledge', 'supreme-person'],
    reviewed: false,
  },
  '7.26': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'supreme-person'],
    reviewed: false,
  },
  '7.27': {
    theme: 'Knowledge and realization',
    concepts: ['illusion', 'desire', 'bondage'],
    reviewed: false,
  },
  '7.28': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'transcendence', 'illusion'],
    reviewed: false,
  },
  '7.29': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'liberation', 'devotion', 'knowledge'],
    reviewed: false,
  },
  '7.30': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'remembrance', 'supreme-person'],
    reviewed: false,
  },
  '8.1': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'supreme-person', 'soul'],
    reviewed: false,
  },
  '8.2': {
    theme: 'Soul and self',
    concepts: ['death', 'remembrance', 'knowledge'],
    reviewed: false,
  },
  '8.3': {
    theme: 'Soul and self',
    concepts: ['soul', 'action', 'transcendence'],
    reviewed: false,
  },
  '8.4': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'impermanence', 'unity'],
    reviewed: false,
  },
  '8.6': {
    theme: 'Devotion and surrender',
    concepts: ['remembrance', 'death', 'meditation'],
    reviewed: false,
  },
  '8.7': {
    theme: 'Devotion and surrender',
    concepts: ['remembrance', 'devotion', 'duty', 'surrender'],
    reviewed: false,
  },
  '8.8': {
    theme: 'Devotion and surrender',
    concepts: ['remembrance', 'meditation', 'devotion', 'supreme-person'],
    reviewed: false,
  },
  '8.9': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'meditation', 'remembrance'],
    reviewed: false,
  },
  '8.10': {
    theme: 'Devotion and surrender',
    concepts: ['remembrance', 'death', 'devotion', 'meditation'],
    reviewed: false,
  },
  '8.11': {
    theme: 'Final liberation',
    concepts: ['liberation', 'renunciation', 'self-realization'],
    reviewed: false,
  },
  '8.12': {
    theme: 'Meditation and mind',
    concepts: ['meditation', 'discipline', 'renunciation'],
    reviewed: false,
  },
  '8.13': {
    theme: 'Devotion and surrender',
    concepts: ['remembrance', 'death', 'liberation'],
    reviewed: false,
  },
  '8.14': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'remembrance', 'grace'],
    reviewed: false,
  },
  '8.15': {
    theme: 'Final liberation',
    concepts: ['liberation', 'devotion', 'impermanence'],
    reviewed: false,
  },
  '8.16': {
    theme: 'Soul and self',
    concepts: ['liberation', 'impermanence', 'death'],
    reviewed: false,
  },
  '8.17': {
    theme: 'Soul and self',
    concepts: ['impermanence', 'knowledge'],
    reviewed: false,
  },
  '8.18': {
    theme: 'Soul and self',
    concepts: ['impermanence', 'death'],
    reviewed: false,
  },
  '8.19': {
    theme: 'Soul and self',
    concepts: ['impermanence', 'death'],
    reviewed: false,
  },
  '8.20': {
    theme: 'Final liberation',
    concepts: ['transcendence', 'impermanence', 'liberation'],
    reviewed: false,
  },
  '8.21': {
    theme: 'Final liberation',
    concepts: ['liberation', 'transcendence', 'supreme-person'],
    reviewed: false,
  },
  '8.22': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['devotion', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '8.23': {
    theme: 'Soul and self',
    concepts: ['death', 'liberation', 'bondage'],
    reviewed: false,
  },
  '8.24': {
    theme: 'Soul and self',
    concepts: ['death', 'liberation', 'knowledge'],
    reviewed: false,
  },
  '8.25': {
    theme: 'Soul and self',
    concepts: ['death', 'bondage', 'liberation'],
    reviewed: false,
  },
  '8.26': {
    theme: 'Final liberation',
    concepts: ['liberation', 'death', 'transcendence'],
    reviewed: false,
  },
  '8.27': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'transcendence', 'illusion'],
    reviewed: false,
  },
  '8.28': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'liberation', 'action'],
    reviewed: false,
  },
  '9.1': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'liberation', 'grace'],
    reviewed: false,
  },
  '9.2': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'self-realization', 'dharma'],
    reviewed: false,
  },
  '9.3': {
    theme: 'Faith and character',
    concepts: ['faith', 'devotion', 'liberation'],
    reviewed: false,
  },
  '9.4': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'unity', 'transcendence'],
    reviewed: false,
  },
  '9.5': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'transcendence', 'opulence'],
    reviewed: false,
  },
  '9.6': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['unity', 'supreme-person', 'knowledge'],
    reviewed: false,
  },
  '9.7': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'impermanence', 'unity'],
    reviewed: false,
  },
  '9.8': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'impermanence'],
    reviewed: false,
  },
  '9.9': {
    theme: 'Duty and action',
    concepts: ['detachment', 'action', 'attachment'],
    reviewed: false,
  },
  '9.10': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'impermanence'],
    reviewed: false,
  },
  '9.11': {
    theme: 'Knowledge and realization',
    concepts: ['supreme-person', 'knowledge', 'illusion'],
    reviewed: false,
  },
  '9.12': {
    theme: 'Knowledge and realization',
    concepts: ['illusion', 'knowledge', 'liberation'],
    reviewed: false,
  },
  '9.13': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'supreme-person', 'surrender'],
    reviewed: false,
  },
  '9.14': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'remembrance', 'surrender'],
    reviewed: false,
  },
  '9.15': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'knowledge', 'supreme-person'],
    reviewed: false,
  },
  '9.16': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['sacrifice', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '9.17': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'knowledge', 'unity'],
    reviewed: false,
  },
  '9.18': {
    theme: 'Devotion and surrender',
    concepts: ['supreme-person', 'surrender', 'grace'],
    reviewed: false,
  },
  '9.19': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'transcendence', 'unity'],
    reviewed: false,
  },
  '9.20': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'desire', 'action'],
    reviewed: false,
  },
  '9.21': {
    theme: 'Modes of nature',
    concepts: ['bondage', 'desire', 'impermanence'],
    reviewed: false,
  },
  '9.23': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'supreme-person', 'faith'],
    reviewed: false,
  },
  '9.24': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'knowledge', 'supreme-person'],
    reviewed: false,
  },
  '9.25': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'liberation', 'surrender'],
    reviewed: false,
  },
  '9.26': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'sacrifice', 'surrender'],
    reviewed: false,
  },
  '9.28': {
    theme: 'Duty and action',
    concepts: ['liberation', 'renunciation', 'bondage', 'detachment'],
    reviewed: false,
  },
  '9.29': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'equanimity', 'transcendence'],
    reviewed: false,
  },
  '9.30': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'surrender', 'transcendence'],
    reviewed: false,
  },
  '9.31': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'grace', 'dharma'],
    reviewed: false,
  },
  '9.32': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'liberation', 'devotion', 'grace'],
    reviewed: false,
  },
  '9.33': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'impermanence', 'surrender'],
    reviewed: false,
  },
  '9.34': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'remembrance', 'surrender'],
    reviewed: false,
  },
  '10.1': {
    theme: 'Devotion and surrender',
    concepts: ['knowledge', 'devotion', 'grace'],
    reviewed: false,
  },
  '10.2': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'knowledge'],
    reviewed: false,
  },
  '10.3': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'supreme-person', 'liberation'],
    reviewed: false,
  },
  '10.4': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'opulence', 'knowledge'],
    reviewed: false,
  },
  '10.5': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'opulence', 'wisdom'],
    reviewed: false,
  },
  '10.6': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person'],
    reviewed: false,
  },
  '10.7': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'opulence', 'knowledge'],
    reviewed: false,
  },
  '10.8': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'knowledge', 'supreme-person'],
    reviewed: false,
  },
  '10.9': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'remembrance', 'surrender'],
    reviewed: false,
  },
  '10.10': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'grace', 'wisdom'],
    reviewed: false,
  },
  '10.11': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'grace', 'illusion'],
    reviewed: false,
  },
  '10.12': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'opulence', 'transcendence'],
    reviewed: false,
  },
  '10.13': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'opulence', 'transcendence'],
    reviewed: false,
  },
  '10.14': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'supreme-person', 'faith'],
    reviewed: false,
  },
  '10.15': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'knowledge', 'opulence'],
    reviewed: false,
  },
  '10.16': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.17': {
    theme: 'Devotion and surrender',
    concepts: ['remembrance', 'devotion', 'knowledge'],
    reviewed: false,
  },
  '10.18': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'devotion', 'supreme-person'],
    reviewed: false,
  },
  '10.19': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person'],
    reviewed: false,
  },
  '10.21': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.22': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.23': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.24': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.25': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'sacrifice'],
    reviewed: false,
  },
  '10.26': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.27': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person'],
    reviewed: false,
  },
  '10.28': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.29': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.30': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.31': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.32': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'knowledge', 'supreme-person'],
    reviewed: false,
  },
  '10.33': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person'],
    reviewed: false,
  },
  '10.34': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'death'],
    reviewed: false,
  },
  '10.35': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person'],
    reviewed: false,
  },
  '10.36': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.37': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '10.38': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'wisdom', 'dharma'],
    reviewed: false,
  },
  '10.39': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'opulence', 'unity'],
    reviewed: false,
  },
  '10.40': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person'],
    reviewed: false,
  },
  '10.41': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['opulence', 'supreme-person', 'knowledge'],
    reviewed: false,
  },
  '10.42': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'unity', 'opulence'],
    reviewed: false,
  },
  '11.1': {
    theme: 'Knowledge and realization',
    concepts: ['illusion', 'knowledge', 'grace'],
    reviewed: false,
  },
  '11.2': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'impermanence', 'supreme-person'],
    reviewed: false,
  },
  '11.3': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'supreme-person', 'devotion'],
    reviewed: false,
  },
  '11.4': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'supreme-person', 'devotion'],
    reviewed: false,
  },
  '11.5': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'opulence', 'supreme-person'],
    reviewed: false,
  },
  '11.6': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'supreme-person', 'opulence'],
    reviewed: false,
  },
  '11.7': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'unity', 'supreme-person'],
    reviewed: false,
  },
  '11.8': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'supreme-person', 'opulence'],
    reviewed: false,
  },
  '11.9': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'supreme-person'],
    reviewed: false,
  },
  '11.10': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'opulence', 'supreme-person'],
    reviewed: false,
  },
  '11.11': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'opulence', 'supreme-person'],
    reviewed: false,
  },
  '11.12': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'supreme-person'],
    reviewed: false,
  },
  '11.13': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'unity', 'supreme-person'],
    reviewed: false,
  },
  '11.14': {
    theme: 'Devotion and surrender',
    concepts: ['universal-form', 'devotion', 'surrender'],
    reviewed: false,
  },
  '11.15': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'unity', 'supreme-person'],
    reviewed: false,
  },
  '11.16': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '11.17': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'supreme-person', 'opulence'],
    reviewed: false,
  },
  '11.18': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'universal-form', 'dharma'],
    reviewed: false,
  },
  '11.19': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'supreme-person', 'opulence'],
    reviewed: false,
  },
  '11.20': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['universal-form', 'unity', 'supreme-person'],
    reviewed: false,
  },
  '11.21': {
    theme: 'Devotion and surrender',
    concepts: ['universal-form', 'surrender', 'devotion'],
    reviewed: false,
  },
  '11.22': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'supreme-person'],
    reviewed: false,
  },
  '11.23': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'grief', 'supreme-person'],
    reviewed: false,
  },
  '11.24': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'grief', 'supreme-person'],
    reviewed: false,
  },
  '11.25': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'surrender', 'grief'],
    reviewed: false,
  },
  '11.26': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'war', 'death'],
    reviewed: false,
  },
  '11.27': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'war', 'death'],
    reviewed: false,
  },
  '11.28': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'war', 'death'],
    reviewed: false,
  },
  '11.29': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'death', 'supreme-person'],
    reviewed: false,
  },
  '11.30': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'death', 'supreme-person'],
    reviewed: false,
  },
  '11.31': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'knowledge', 'devotion'],
    reviewed: false,
  },
  '11.32': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'death', 'universal-form'],
    reviewed: false,
  },
  '11.33': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'action', 'supreme-person'],
    reviewed: false,
  },
  '11.34': {
    theme: 'Arjuna\'s dilemma',
    concepts: ['war', 'death', 'universal-form'],
    reviewed: false,
  },
  '11.35': {
    theme: 'Devotion and surrender',
    concepts: ['universal-form', 'devotion', 'surrender'],
    reviewed: false,
  },
  '11.36': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'universal-form', 'supreme-person'],
    reviewed: false,
  },
  '11.37': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'universal-form', 'transcendence'],
    reviewed: false,
  },
  '11.38': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'universal-form', 'transcendence'],
    reviewed: false,
  },
  '11.39': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'devotion', 'supreme-person'],
    reviewed: false,
  },
  '11.40': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'devotion', 'unity'],
    reviewed: false,
  },
  '11.41': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'surrender', 'ego'],
    reviewed: false,
  },
  '11.42': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'surrender', 'ego'],
    reviewed: false,
  },
  '11.43': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'universal-form', 'devotion'],
    reviewed: false,
  },
  '11.44': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'surrender', 'grace'],
    reviewed: false,
  },
  '11.45': {
    theme: 'Devotion and surrender',
    concepts: ['universal-form', 'surrender', 'grace'],
    reviewed: false,
  },
  '11.46': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'devotion', 'desire'],
    reviewed: false,
  },
  '11.47': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'supreme-person', 'grace'],
    reviewed: false,
  },
  '11.48': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'supreme-person', 'sacrifice'],
    reviewed: false,
  },
  '11.49': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'grace', 'grief'],
    reviewed: false,
  },
  '11.50': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'supreme-person', 'grace'],
    reviewed: false,
  },
  '11.51': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'equanimity', 'transcendence'],
    reviewed: false,
  },
  '11.52': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'supreme-person'],
    reviewed: false,
  },
  '11.53': {
    theme: 'Cosmic vision',
    concepts: ['universal-form', 'knowledge', 'austerity'],
    reviewed: false,
  },
  '11.55': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'surrender', 'detachment'],
    reviewed: false,
  },
  '12.1': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'supreme-person', 'knowledge'],
    reviewed: false,
  },
  '12.2': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'faith', 'meditation'],
    reviewed: false,
  },
  '12.3': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'discipline', 'transcendence'],
    reviewed: false,
  },
  '12.4': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'discipline', 'transcendence'],
    reviewed: false,
  },
  '12.5': {
    theme: 'Meditation and mind',
    concepts: ['attachment', 'devotion', 'discipline'],
    reviewed: false,
  },
  '12.6': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'grace', 'liberation', 'surrender'],
    reviewed: false,
  },
  '12.7': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'grace', 'liberation', 'surrender'],
    reviewed: false,
  },
  '12.9': {
    theme: 'Meditation and mind',
    concepts: ['devotion', 'discipline', 'meditation'],
    reviewed: false,
  },
  '12.10': {
    theme: 'Duty and action',
    concepts: ['devotion', 'action', 'karma-yoga'],
    reviewed: false,
  },
  '12.11': {
    theme: 'Duty and action',
    concepts: ['detachment', 'karma-yoga', 'action', 'renunciation'],
    reviewed: false,
  },
  '12.12': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'detachment', 'meditation', 'knowledge'],
    reviewed: false,
  },
  '12.14': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'equanimity', 'compassion'],
    reviewed: false,
  },
  '12.15': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'transcendence', 'devotion'],
    reviewed: false,
  },
  '12.16': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'detachment', 'equanimity'],
    reviewed: false,
  },
  '12.17': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'devotion', 'renunciation', 'transcendence'],
    reviewed: false,
  },
  '12.18': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'devotion', 'transcendence'],
    reviewed: false,
  },
  '12.19': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'devotion', 'transcendence'],
    reviewed: false,
  },
  '12.20': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'faith', 'surrender'],
    reviewed: false,
  },
  '13.1': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'soul', 'self-realization'],
    reviewed: false,
  },
  '13.2': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'soul', 'self-realization'],
    reviewed: false,
  },
  '13.3': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'unity', 'soul'],
    reviewed: false,
  },
  '13.4': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'soul', 'supreme-person'],
    reviewed: false,
  },
  '13.5': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'soul'],
    reviewed: false,
  },
  '13.6': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'ego', 'knowledge'],
    reviewed: false,
  },
  '13.7': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'ego', 'knowledge'],
    reviewed: false,
  },
  '13.9': {
    theme: 'Meditation and mind',
    concepts: ['knowledge', 'devotion', 'equanimity', 'attachment'],
    reviewed: false,
  },
  '13.10': {
    theme: 'Meditation and mind',
    concepts: ['knowledge', 'devotion', 'equanimity', 'attachment'],
    reviewed: false,
  },
  '13.11': {
    theme: 'Meditation and mind',
    concepts: ['knowledge', 'devotion', 'equanimity', 'attachment'],
    reviewed: false,
  },
  '13.12': {
    theme: 'Meditation and mind',
    concepts: ['knowledge', 'devotion', 'equanimity', 'attachment'],
    reviewed: false,
  },
  '13.13': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'supreme-person', 'transcendence'],
    reviewed: false,
  },
  '13.14': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['unity', 'supreme-person', 'knowledge'],
    reviewed: false,
  },
  '13.15': {
    theme: 'Final liberation',
    concepts: ['transcendence', 'supreme-person', 'modes-of-nature'],
    reviewed: false,
  },
  '13.16': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['unity', 'knowledge', 'supreme-person'],
    reviewed: false,
  },
  '13.17': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['unity', 'knowledge', 'supreme-person'],
    reviewed: false,
  },
  '13.18': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'transcendence', 'supreme-person'],
    reviewed: false,
  },
  '13.19': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'devotion', 'self-realization'],
    reviewed: false,
  },
  '13.20': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'modes-of-nature', 'soul'],
    reviewed: false,
  },
  '13.21': {
    theme: 'Soul and self',
    concepts: ['soul', 'impermanence'],
    reviewed: false,
  },
  '13.22': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'bondage', 'attachment'],
    reviewed: false,
  },
  '13.23': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'knowledge', 'transcendence'],
    reviewed: false,
  },
  '13.24': {
    theme: 'Final liberation',
    concepts: ['liberation', 'knowledge', 'transcendence'],
    reviewed: false,
  },
  '13.25': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'meditation', 'karma-yoga'],
    reviewed: false,
  },
  '13.26': {
    theme: 'Final liberation',
    concepts: ['liberation', 'devotion', 'transcendence'],
    reviewed: false,
  },
  '13.27': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'soul', 'self-realization'],
    reviewed: false,
  },
  '13.28': {
    theme: 'Soul and self',
    concepts: ['soul', 'knowledge', 'unity'],
    reviewed: false,
  },
  '13.29': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['unity', 'knowledge', 'liberation'],
    reviewed: false,
  },
  '13.30': {
    theme: 'Duty and action',
    concepts: ['action', 'knowledge', 'soul'],
    reviewed: false,
  },
  '13.31': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['unity', 'knowledge', 'liberation'],
    reviewed: false,
  },
  '13.32': {
    theme: 'Soul and self',
    concepts: ['soul', 'transcendence', 'knowledge'],
    reviewed: false,
  },
  '13.33': {
    theme: 'Knowledge and realization',
    concepts: ['soul', 'knowledge', 'self-realization'],
    reviewed: false,
  },
  '13.34': {
    theme: 'Knowledge and realization',
    concepts: ['soul', 'knowledge', 'self-realization'],
    reviewed: false,
  },
  '13.35': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'liberation', 'soul'],
    reviewed: false,
  },
  '14.1': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'self-realization', 'wisdom'],
    reviewed: false,
  },
  '14.2': {
    theme: 'Final liberation',
    concepts: ['liberation', 'transcendence', 'knowledge'],
    reviewed: false,
  },
  '14.3': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'modes-of-nature'],
    reviewed: false,
  },
  '14.4': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'modes-of-nature'],
    reviewed: false,
  },
  '14.5': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'bondage', 'soul'],
    reviewed: false,
  },
  '14.6': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'bondage', 'purity'],
    reviewed: false,
  },
  '14.7': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'bondage', 'modes-of-nature', 'attachment'],
    reviewed: false,
  },
  '14.8': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'bondage', 'illusion'],
    reviewed: false,
  },
  '14.9': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'bondage', 'illusion'],
    reviewed: false,
  },
  '14.10': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'impermanence'],
    reviewed: false,
  },
  '14.11': {
    theme: 'Knowledge and realization',
    concepts: ['modes-of-nature', 'knowledge', 'wisdom'],
    reviewed: false,
  },
  '14.12': {
    theme: 'Meditation and mind',
    concepts: ['modes-of-nature', 'desire', 'attachment'],
    reviewed: false,
  },
  '14.13': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'illusion'],
    reviewed: false,
  },
  '14.14': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'death', 'purity'],
    reviewed: false,
  },
  '14.15': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'death', 'bondage'],
    reviewed: false,
  },
  '14.16': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'action', 'purity'],
    reviewed: false,
  },
  '14.17': {
    theme: 'Knowledge and realization',
    concepts: ['modes-of-nature', 'knowledge', 'illusion'],
    reviewed: false,
  },
  '14.18': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'bondage', 'purity'],
    reviewed: false,
  },
  '14.19': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'transcendence', 'knowledge'],
    reviewed: false,
  },
  '14.20': {
    theme: 'Final liberation',
    concepts: ['transcendence', 'modes-of-nature', 'liberation'],
    reviewed: false,
  },
  '14.21': {
    theme: 'Final liberation',
    concepts: ['transcendence', 'modes-of-nature', 'self-realization'],
    reviewed: false,
  },
  '14.23': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'modes-of-nature', 'transcendence'],
    reviewed: false,
  },
  '14.24': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'transcendence', 'modes-of-nature'],
    reviewed: false,
  },
  '14.25': {
    theme: 'Final liberation',
    concepts: ['transcendence', 'equanimity', 'modes-of-nature'],
    reviewed: false,
  },
  '14.26': {
    theme: 'Final liberation',
    concepts: ['devotion', 'transcendence', 'modes-of-nature', 'liberation'],
    reviewed: false,
  },
  '14.27': {
    theme: 'Final liberation',
    concepts: ['supreme-person', 'transcendence', 'liberation'],
    reviewed: false,
  },
  '15.1': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'supreme-person', 'transcendence'],
    reviewed: false,
  },
  '15.2': {
    theme: 'Modes of nature',
    concepts: ['bondage', 'modes-of-nature', 'attachment'],
    reviewed: false,
  },
  '15.3': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'liberation', 'renunciation', 'supreme-person'],
    reviewed: false,
  },
  '15.4': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'liberation', 'supreme-person', 'renunciation'],
    reviewed: false,
  },
  '15.5': {
    theme: 'Final liberation',
    concepts: ['liberation', 'transcendence', 'surrender', 'illusion'],
    reviewed: false,
  },
  '15.6': {
    theme: 'Final liberation',
    concepts: ['liberation', 'transcendence', 'supreme-person'],
    reviewed: false,
  },
  '15.8': {
    theme: 'Soul and self',
    concepts: ['soul', 'impermanence', 'death'],
    reviewed: false,
  },
  '15.9': {
    theme: 'Soul and self',
    concepts: ['soul', 'death', 'impermanence'],
    reviewed: false,
  },
  '15.10': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'death', 'illusion'],
    reviewed: false,
  },
  '15.11': {
    theme: 'Knowledge and realization',
    concepts: ['self-realization', 'knowledge', 'illusion'],
    reviewed: false,
  },
  '15.12': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'opulence', 'unity'],
    reviewed: false,
  },
  '15.13': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'unity', 'opulence'],
    reviewed: false,
  },
  '15.14': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'unity'],
    reviewed: false,
  },
  '15.15': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'knowledge', 'unity'],
    reviewed: false,
  },
  '15.16': {
    theme: 'Final liberation',
    concepts: ['transcendence', 'soul', 'supreme-person'],
    reviewed: false,
  },
  '15.17': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'soul', 'unity'],
    reviewed: false,
  },
  '15.18': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'transcendence'],
    reviewed: false,
  },
  '15.19': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'knowledge', 'supreme-person'],
    reviewed: false,
  },
  '15.20': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'wisdom', 'self-realization'],
    reviewed: false,
  },
  '16.2': {
    theme: 'Faith and character',
    concepts: ['purity', 'compassion', 'austerity'],
    reviewed: false,
  },
  '16.3': {
    theme: 'Faith and character',
    concepts: ['purity', 'compassion', 'austerity'],
    reviewed: false,
  },
  '16.4': {
    theme: 'Meditation and mind',
    concepts: ['anger', 'ego'],
    reviewed: false,
  },
  '16.5': {
    theme: 'Final liberation',
    concepts: ['liberation', 'bondage', 'purity'],
    reviewed: false,
  },
  '16.6': {
    theme: 'Faith and character',
    concepts: ['purity', 'compassion'],
    reviewed: false,
  },
  '16.7': {
    theme: 'Duty and action',
    concepts: ['purity', 'dharma', 'action'],
    reviewed: false,
  },
  '16.8': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'illusion'],
    reviewed: false,
  },
  '16.9': {
    theme: 'Duty and action',
    concepts: ['action', 'purity', 'illusion'],
    reviewed: false,
  },
  '16.10': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'ego', 'illusion'],
    reviewed: false,
  },
  '16.11': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'anger', 'bondage'],
    reviewed: false,
  },
  '16.12': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'anger', 'bondage'],
    reviewed: false,
  },
  '16.13': {
    theme: 'Meditation and mind',
    concepts: ['ego', 'illusion', 'desire'],
    reviewed: false,
  },
  '16.14': {
    theme: 'Meditation and mind',
    concepts: ['ego', 'illusion', 'desire'],
    reviewed: false,
  },
  '16.15': {
    theme: 'Meditation and mind',
    concepts: ['ego', 'illusion', 'desire'],
    reviewed: false,
  },
  '16.16': {
    theme: 'Meditation and mind',
    concepts: ['attachment', 'desire', 'illusion'],
    reviewed: false,
  },
  '16.17': {
    theme: 'Meditation and mind',
    concepts: ['ego', 'illusion', 'sacrifice'],
    reviewed: false,
  },
  '16.18': {
    theme: 'Meditation and mind',
    concepts: ['ego', 'anger', 'supreme-person'],
    reviewed: false,
  },
  '16.19': {
    theme: 'Modes of nature',
    concepts: ['bondage', 'purity', 'supreme-person'],
    reviewed: false,
  },
  '16.20': {
    theme: 'Modes of nature',
    concepts: ['bondage', 'purity', 'liberation'],
    reviewed: false,
  },
  '16.21': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'anger', 'renunciation'],
    reviewed: false,
  },
  '16.22': {
    theme: 'Final liberation',
    concepts: ['liberation', 'self-realization', 'transcendence'],
    reviewed: false,
  },
  '16.23': {
    theme: 'Duty and action',
    concepts: ['desire', 'dharma', 'action'],
    reviewed: false,
  },
  '16.24': {
    theme: 'Duty and action',
    concepts: ['action', 'dharma', 'duty'],
    reviewed: false,
  },
  '17.1': {
    theme: 'Faith and character',
    concepts: ['faith', 'modes-of-nature', 'dharma'],
    reviewed: false,
  },
  '17.2': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'faith'],
    reviewed: false,
  },
  '17.4': {
    theme: 'Faith and character',
    concepts: ['modes-of-nature', 'faith', 'purity'],
    reviewed: false,
  },
  '17.5': {
    theme: 'Meditation and mind',
    concepts: ['austerity', 'ego', 'desire'],
    reviewed: false,
  },
  '17.6': {
    theme: 'Meditation and mind',
    concepts: ['austerity', 'ego', 'desire'],
    reviewed: false,
  },
  '17.7': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'charity', 'sacrifice'],
    reviewed: false,
  },
  '17.8': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'purity'],
    reviewed: false,
  },
  '17.9': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'bondage'],
    reviewed: false,
  },
  '17.10': {
    theme: 'Faith and character',
    concepts: ['modes-of-nature', 'purity', 'faith'],
    reviewed: false,
  },
  '17.11': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'detachment', 'karma-yoga'],
    reviewed: false,
  },
  '17.12': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'modes-of-nature', 'desire'],
    reviewed: false,
  },
  '17.13': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'faith', 'modes-of-nature'],
    reviewed: false,
  },
  '17.14': {
    theme: 'Faith and character',
    concepts: ['austerity', 'devotion', 'purity'],
    reviewed: false,
  },
  '17.15': {
    theme: 'Faith and character',
    concepts: ['austerity', 'discipline'],
    reviewed: false,
  },
  '17.16': {
    theme: 'Faith and character',
    concepts: ['austerity', 'discipline', 'purity'],
    reviewed: false,
  },
  '17.17': {
    theme: 'Faith and character',
    concepts: ['austerity', 'faith', 'detachment'],
    reviewed: false,
  },
  '17.18': {
    theme: 'Faith and character',
    concepts: ['austerity', 'modes-of-nature', 'ego'],
    reviewed: false,
  },
  '17.19': {
    theme: 'Faith and character',
    concepts: ['austerity', 'modes-of-nature', 'action'],
    reviewed: false,
  },
  '17.20': {
    theme: 'Faith and character',
    concepts: ['charity', 'modes-of-nature', 'detachment'],
    reviewed: false,
  },
  '17.21': {
    theme: 'Faith and character',
    concepts: ['charity', 'modes-of-nature', 'desire'],
    reviewed: false,
  },
  '17.22': {
    theme: 'Faith and character',
    concepts: ['charity', 'modes-of-nature', 'purity'],
    reviewed: false,
  },
  '17.23': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'faith'],
    reviewed: false,
  },
  '17.24': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'charity', 'action'],
    reviewed: false,
  },
  '17.25': {
    theme: 'Duty and action',
    concepts: ['detachment', 'sacrifice', 'liberation', 'karma-yoga'],
    reviewed: false,
  },
  '17.26': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'devotion', 'supreme-person'],
    reviewed: false,
  },
  '17.27': {
    theme: 'Duty and action',
    concepts: ['sacrifice', 'devotion', 'supreme-person'],
    reviewed: false,
  },
  '17.28': {
    theme: 'Faith and character',
    concepts: ['faith', 'sacrifice', 'charity'],
    reviewed: false,
  },
  '18.1': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'knowledge'],
    reviewed: false,
  },
  '18.2': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'detachment', 'action', 'desire'],
    reviewed: false,
  },
  '18.3': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'action', 'sacrifice'],
    reviewed: false,
  },
  '18.4': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'detachment'],
    reviewed: false,
  },
  '18.5': {
    theme: 'Faith and character',
    concepts: ['sacrifice', 'charity', 'austerity'],
    reviewed: false,
  },
  '18.6': {
    theme: 'Duty and action',
    concepts: ['detachment', 'karma-yoga', 'action', 'attachment'],
    reviewed: false,
  },
  '18.7': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'duty', 'action', 'illusion'],
    reviewed: false,
  },
  '18.8': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'action', 'duty', 'modes-of-nature'],
    reviewed: false,
  },
  '18.9': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'detachment', 'duty', 'attachment'],
    reviewed: false,
  },
  '18.10': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'action', 'detachment', 'equanimity'],
    reviewed: false,
  },
  '18.11': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'action', 'detachment', 'karma-yoga'],
    reviewed: false,
  },
  '18.12': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'action', 'detachment'],
    reviewed: false,
  },
  '18.13': {
    theme: 'Duty and action',
    concepts: ['action', 'renunciation'],
    reviewed: false,
  },
  '18.14': {
    theme: 'Duty and action',
    concepts: ['action', 'supreme-person'],
    reviewed: false,
  },
  '18.15': {
    theme: 'Duty and action',
    concepts: ['action', 'ego'],
    reviewed: false,
  },
  '18.16': {
    theme: 'Meditation and mind',
    concepts: ['ego', 'action', 'knowledge'],
    reviewed: false,
  },
  '18.17': {
    theme: 'Meditation and mind',
    concepts: ['ego', 'action', 'bondage'],
    reviewed: false,
  },
  '18.18': {
    theme: 'Knowledge and realization',
    concepts: ['action', 'knowledge', 'wisdom'],
    reviewed: false,
  },
  '18.19': {
    theme: 'Duty and action',
    concepts: ['action', 'modes-of-nature', 'knowledge'],
    reviewed: false,
  },
  '18.20': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'unity', 'soul'],
    reviewed: false,
  },
  '18.21': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'modes-of-nature', 'soul'],
    reviewed: false,
  },
  '18.22': {
    theme: 'Meditation and mind',
    concepts: ['attachment', 'knowledge', 'modes-of-nature'],
    reviewed: false,
  },
  '18.23': {
    theme: 'Duty and action',
    concepts: ['action', 'detachment', 'attachment', 'karma-yoga'],
    reviewed: false,
  },
  '18.24': {
    theme: 'Meditation and mind',
    concepts: ['action', 'desire', 'ego', 'modes-of-nature'],
    reviewed: false,
  },
  '18.25': {
    theme: 'Duty and action',
    concepts: ['action', 'illusion', 'modes-of-nature'],
    reviewed: false,
  },
  '18.26': {
    theme: 'Duty and action',
    concepts: ['action', 'equanimity', 'duty'],
    reviewed: false,
  },
  '18.27': {
    theme: 'Meditation and mind',
    concepts: ['desire', 'attachment', 'modes-of-nature', 'action'],
    reviewed: false,
  },
  '18.28': {
    theme: 'Duty and action',
    concepts: ['action', 'modes-of-nature', 'dharma'],
    reviewed: false,
  },
  '18.29': {
    theme: 'Knowledge and realization',
    concepts: ['modes-of-nature', 'wisdom', 'knowledge'],
    reviewed: false,
  },
  '18.30': {
    theme: 'Knowledge and realization',
    concepts: ['wisdom', 'action', 'knowledge'],
    reviewed: false,
  },
  '18.31': {
    theme: 'Duty and action',
    concepts: ['modes-of-nature', 'dharma', 'action'],
    reviewed: false,
  },
  '18.32': {
    theme: 'Knowledge and realization',
    concepts: ['illusion', 'dharma', 'modes-of-nature'],
    reviewed: false,
  },
  '18.33': {
    theme: 'Meditation and mind',
    concepts: ['discipline', 'modes-of-nature', 'meditation'],
    reviewed: false,
  },
  '18.34': {
    theme: 'Meditation and mind',
    concepts: ['modes-of-nature', 'attachment', 'desire'],
    reviewed: false,
  },
  '18.35': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'illusion', 'grief'],
    reviewed: false,
  },
  '18.36': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'discipline'],
    reviewed: false,
  },
  '18.37': {
    theme: 'Knowledge and realization',
    concepts: ['self-realization', 'modes-of-nature', 'renunciation'],
    reviewed: false,
  },
  '18.38': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'attachment', 'impermanence'],
    reviewed: false,
  },
  '18.39': {
    theme: 'Knowledge and realization',
    concepts: ['illusion', 'modes-of-nature', 'self-realization'],
    reviewed: false,
  },
  '18.40': {
    theme: 'Modes of nature',
    concepts: ['modes-of-nature', 'bondage', 'liberation'],
    reviewed: false,
  },
  '18.41': {
    theme: 'Duty and action',
    concepts: ['modes-of-nature', 'duty', 'action'],
    reviewed: false,
  },
  '18.42': {
    theme: 'Faith and character',
    concepts: ['austerity', 'discipline', 'purity'],
    reviewed: false,
  },
  '18.43': {
    theme: 'Duty and action',
    concepts: ['duty', 'action', 'dharma'],
    reviewed: false,
  },
  '18.44': {
    theme: 'Duty and action',
    concepts: ['duty', 'action', 'dharma'],
    reviewed: false,
  },
  '18.45': {
    theme: 'Duty and action',
    concepts: ['duty', 'action', 'dharma'],
    reviewed: false,
  },
  '18.47': {
    theme: 'Duty and action',
    concepts: ['duty', 'action', 'dharma'],
    reviewed: false,
  },
  '18.48': {
    theme: 'Duty and action',
    concepts: ['action', 'duty', 'renunciation'],
    reviewed: false,
  },
  '18.49': {
    theme: 'Duty and action',
    concepts: ['renunciation', 'detachment', 'attachment', 'discipline'],
    reviewed: false,
  },
  '18.50': {
    theme: 'Knowledge and realization',
    concepts: ['liberation', 'knowledge', 'self-realization'],
    reviewed: false,
  },
  '18.51': {
    theme: 'Meditation and mind',
    concepts: ['renunciation', 'discipline', 'self-realization', 'attachment'],
    reviewed: false,
  },
  '18.52': {
    theme: 'Meditation and mind',
    concepts: ['renunciation', 'discipline', 'self-realization', 'attachment'],
    reviewed: false,
  },
  '18.53': {
    theme: 'Meditation and mind',
    concepts: ['renunciation', 'discipline', 'self-realization', 'attachment'],
    reviewed: false,
  },
  '18.54': {
    theme: 'Meditation and mind',
    concepts: ['equanimity', 'devotion', 'transcendence', 'self-realization'],
    reviewed: false,
  },
  '18.55': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'liberation', 'supreme-person'],
    reviewed: false,
  },
  '18.56': {
    theme: 'Devotion and surrender',
    concepts: ['grace', 'devotion', 'surrender', 'liberation'],
    reviewed: false,
  },
  '18.57': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'devotion', 'grace', 'action'],
    reviewed: false,
  },
  '18.58': {
    theme: 'Devotion and surrender',
    concepts: ['grace', 'ego', 'surrender'],
    reviewed: false,
  },
  '18.59': {
    theme: 'Duty and action',
    concepts: ['action', 'war', 'duty'],
    reviewed: false,
  },
  '18.60': {
    theme: 'Duty and action',
    concepts: ['action', 'illusion', 'bondage'],
    reviewed: false,
  },
  '18.61': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'bondage', 'unity'],
    reviewed: false,
  },
  '18.62': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'grace', 'liberation'],
    reviewed: false,
  },
  '18.63': {
    theme: 'Knowledge and realization',
    concepts: ['knowledge', 'renunciation', 'wisdom'],
    reviewed: false,
  },
  '18.64': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'knowledge', 'surrender'],
    reviewed: false,
  },
  '18.65': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'surrender', 'remembrance'],
    reviewed: false,
  },
  '18.67': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'knowledge', 'austerity'],
    reviewed: false,
  },
  '18.68': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'liberation', 'surrender'],
    reviewed: false,
  },
  '18.69': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'surrender', 'grace'],
    reviewed: false,
  },
  '18.70': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'knowledge', 'sacrifice'],
    reviewed: false,
  },
  '18.71': {
    theme: 'Faith and character',
    concepts: ['faith', 'liberation', 'devotion'],
    reviewed: false,
  },
  '18.72': {
    theme: 'Knowledge and realization',
    concepts: ['illusion', 'knowledge', 'wisdom'],
    reviewed: false,
  },
  '18.73': {
    theme: 'Devotion and surrender',
    concepts: ['surrender', 'illusion', 'grace'],
    reviewed: false,
  },
  '18.74': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'surrender'],
    reviewed: false,
  },
  '18.75': {
    theme: 'Kṛṣṇa\'s supremacy',
    concepts: ['supreme-person', 'grace'],
    reviewed: false,
  },
  '18.76': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'remembrance'],
    reviewed: false,
  },
  '18.77': {
    theme: 'Devotion and surrender',
    concepts: ['devotion', 'remembrance', 'universal-form'],
    reviewed: false,
  },
};
