import type { VerseCuration } from '../types.js';

// GENERATED by scripts/generate-concepts.mjs — do not edit by hand.
//
// Machine-proposed concepts and placeholder themes for verses that have no
// entry in curation.ts. Every entry is reviewed: false. To accept one, move
// it into curation.ts (which always wins), give it a real theme, and drop
// the flag; to correct it, do the same with the corrected concepts. Rerunning
// the script regenerates only what curation.ts does not cover.
export const generatedCuration: Record<string, VerseCuration> = {
  '1.2': {
    theme: 'Guru & War',
    concepts: ['guru', 'war'],
    reviewed: false,
  },
  '1.3': {
    theme: 'Guru & Wisdom',
    concepts: ['guru', 'wisdom', 'universal-form', 'war'],
    reviewed: false,
  },
  '1.4': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.7': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.8': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.10': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.12': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.14': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.15': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.20': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.21': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.22': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.23': {
    theme: 'War & Desire',
    concepts: ['war', 'desire'],
    reviewed: false,
  },
  '1.24': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.25': {
    theme: 'Universal Form',
    concepts: ['universal-form'],
    reviewed: false,
  },
  '1.26': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.27': {
    theme: 'Compassion',
    concepts: ['compassion'],
    reviewed: false,
  },
  '1.28': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.31': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '1.32': {
    theme: 'Desire & War',
    concepts: ['desire', 'war'],
    reviewed: false,
  },
  '1.33': {
    theme: 'Desire & War',
    concepts: ['desire', 'war'],
    reviewed: false,
  },
  '1.38': {
    theme: 'Desire',
    concepts: ['desire'],
    reviewed: false,
  },
  '1.44': {
    theme: 'Wisdom',
    concepts: ['wisdom'],
    reviewed: false,
  },
  '1.45': {
    theme: 'Desire',
    concepts: ['desire'],
    reviewed: false,
  },
  '1.46': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '2.1': {
    theme: 'Grief & Compassion',
    concepts: ['grief', 'compassion'],
    reviewed: false,
  },
  '2.2': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '2.4': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '2.7': {
    theme: 'Duty & Guru',
    concepts: ['duty', 'guru', 'illusion', 'surrender'],
    reviewed: false,
  },
  '2.9': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '2.10': {
    theme: 'War & Grief',
    concepts: ['war', 'grief'],
    reviewed: false,
  },
  '2.11': {
    theme: 'Grief & Wisdom',
    concepts: ['grief', 'wisdom', 'death', 'supreme-person'],
    reviewed: false,
  },
  '2.13': {
    theme: 'Soul & Illusion',
    concepts: ['soul', 'illusion', 'wisdom'],
    reviewed: false,
  },
  '2.15': {
    theme: 'Equanimity',
    concepts: ['equanimity'],
    reviewed: false,
  },
  '2.17': {
    theme: 'Soul & Unity',
    concepts: ['soul', 'unity'],
    reviewed: false,
  },
  '2.18': {
    theme: 'Soul & War',
    concepts: ['soul', 'war'],
    reviewed: false,
  },
  '2.19': {
    theme: 'Death & Soul',
    concepts: ['death', 'soul', 'knowledge'],
    reviewed: false,
  },
  '2.21': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '2.22': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '2.23': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '2.24': {
    theme: 'Soul & Unity',
    concepts: ['soul', 'unity'],
    reviewed: false,
  },
  '2.25': {
    theme: 'Soul & Grief',
    concepts: ['soul', 'grief'],
    reviewed: false,
  },
  '2.26': {
    theme: 'Grief & Death',
    concepts: ['grief', 'death'],
    reviewed: false,
  },
  '2.27': {
    theme: 'Death & Grief',
    concepts: ['death', 'grief'],
    reviewed: false,
  },
  '2.28': {
    theme: 'Grief',
    concepts: ['grief'],
    reviewed: false,
  },
  '2.29': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '2.30': {
    theme: 'Soul & Grief',
    concepts: ['soul', 'grief'],
    reviewed: false,
  },
  '2.31': {
    theme: 'War & Dharma',
    concepts: ['war', 'dharma', 'duty'],
    reviewed: false,
  },
  '2.32': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '2.33': {
    theme: 'War & Dharma',
    concepts: ['war', 'dharma', 'duty'],
    reviewed: false,
  },
  '2.34': {
    theme: 'Death',
    concepts: ['death'],
    reviewed: false,
  },
  '2.35': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '2.36': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '2.37': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '2.38': {
    theme: 'War & Equanimity',
    concepts: ['war', 'equanimity'],
    reviewed: false,
  },
  '2.39': {
    theme: 'Action & Knowledge',
    concepts: ['action', 'knowledge', 'bondage', 'wisdom'],
    reviewed: false,
  },
  '2.43': {
    theme: 'Opulence',
    concepts: ['opulence'],
    reviewed: false,
  },
  '2.44': {
    theme: 'Attachment',
    concepts: ['attachment'],
    reviewed: false,
  },
  '2.45': {
    theme: 'Modes Of Nature & Soul',
    concepts: ['modes-of-nature', 'soul', 'transcendence'],
    reviewed: false,
  },
  '2.46': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '2.48': {
    theme: 'Equanimity & Attachment',
    concepts: ['equanimity', 'attachment', 'action'],
    reviewed: false,
  },
  '2.49': {
    theme: 'Wisdom & Action',
    concepts: ['wisdom', 'action', 'knowledge', 'surrender'],
    reviewed: false,
  },
  '2.50': {
    theme: 'Wisdom',
    concepts: ['wisdom'],
    reviewed: false,
  },
  '2.51': {
    theme: 'Wisdom & Knowledge',
    concepts: ['wisdom', 'knowledge', 'renunciation'],
    reviewed: false,
  },
  '2.52': {
    theme: 'Illusion',
    concepts: ['illusion'],
    reviewed: false,
  },
  '2.53': {
    theme: 'Self Realization',
    concepts: ['self-realization'],
    reviewed: false,
  },
  '2.54': {
    theme: 'Wisdom',
    concepts: ['wisdom'],
    reviewed: false,
  },
  '2.55': {
    theme: 'Soul & Wisdom',
    concepts: ['soul', 'wisdom', 'supreme-person'],
    reviewed: false,
  },
  '2.57': {
    theme: 'Attachment & Detachment',
    concepts: ['attachment', 'detachment', 'unity'],
    reviewed: false,
  },
  '2.58': {
    theme: 'Wisdom',
    concepts: ['wisdom'],
    reviewed: false,
  },
  '2.59': {
    theme: 'Discipline',
    concepts: ['discipline'],
    reviewed: false,
  },
  '2.60': {
    theme: 'Discipline & Wisdom',
    concepts: ['discipline', 'wisdom'],
    reviewed: false,
  },
  '2.61': {
    theme: 'Discipline',
    concepts: ['discipline'],
    reviewed: false,
  },
  '2.64': {
    theme: 'Soul & Attachment',
    concepts: ['soul', 'attachment'],
    reviewed: false,
  },
  '2.65': {
    theme: 'Equanimity',
    concepts: ['equanimity'],
    reviewed: false,
  },
  '2.66': {
    theme: 'Meditation & Unity',
    concepts: ['meditation', 'unity', 'equanimity'],
    reviewed: false,
  },
  '2.68': {
    theme: 'Knowledge',
    concepts: ['knowledge'],
    reviewed: false,
  },
  '2.70': {
    theme: 'Equanimity',
    concepts: ['equanimity'],
    reviewed: false,
  },
  '2.71': {
    theme: 'Ego & Equanimity',
    concepts: ['ego', 'equanimity', 'desire'],
    reviewed: false,
  },
  '2.72': {
    theme: 'Illusion & Soul',
    concepts: ['illusion', 'soul', 'unity'],
    reviewed: false,
  },
  '3.1': {
    theme: 'Action & Universal Form',
    concepts: ['action', 'universal-form'],
    reviewed: false,
  },
  '3.3': {
    theme: 'Action & Knowledge',
    concepts: ['action', 'knowledge', 'purity'],
    reviewed: false,
  },
  '3.4': {
    theme: 'Renunciation & Self Realization',
    concepts: ['renunciation', 'self-realization'],
    reviewed: false,
  },
  '3.6': {
    theme: 'Illusion & Action',
    concepts: ['illusion', 'action', 'soul'],
    reviewed: false,
  },
  '3.7': {
    theme: 'Detachment & Action',
    concepts: ['detachment', 'action', 'attachment', 'karma-yoga'],
    reviewed: false,
  },
  '3.8': {
    theme: 'Duty & Action',
    concepts: ['duty', 'action'],
    reviewed: false,
  },
  '3.9': {
    theme: 'Sacrifice & Action',
    concepts: ['sacrifice', 'action', 'attachment', 'detachment'],
    reviewed: false,
  },
  '3.10': {
    theme: 'Sacrifice',
    concepts: ['sacrifice'],
    reviewed: false,
  },
  '3.12': {
    theme: 'Sacrifice',
    concepts: ['sacrifice'],
    reviewed: false,
  },
  '3.13': {
    theme: 'Sacrifice',
    concepts: ['sacrifice'],
    reviewed: false,
  },
  '3.14': {
    theme: 'Sacrifice & Action',
    concepts: ['sacrifice', 'action', 'duty'],
    reviewed: false,
  },
  '3.15': {
    theme: 'Soul & Sacrifice',
    concepts: ['soul', 'sacrifice', 'unity'],
    reviewed: false,
  },
  '3.17': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '3.18': {
    theme: 'Duty',
    concepts: ['duty'],
    reviewed: false,
  },
  '3.20': {
    theme: 'Action & Duty',
    concepts: ['action', 'duty', 'self-realization'],
    reviewed: false,
  },
  '3.22': {
    theme: 'Duty',
    concepts: ['duty'],
    reviewed: false,
  },
  '3.23': {
    theme: 'Duty',
    concepts: ['duty'],
    reviewed: false,
  },
  '3.24': {
    theme: 'Action & Duty',
    concepts: ['action', 'duty'],
    reviewed: false,
  },
  '3.25': {
    theme: 'Attachment & Detachment',
    concepts: ['attachment', 'detachment', 'wisdom', 'action'],
    reviewed: false,
  },
  '3.26': {
    theme: 'Wisdom & Attachment',
    concepts: ['wisdom', 'attachment', 'action', 'illusion'],
    reviewed: false,
  },
  '3.28': {
    theme: 'Modes Of Nature & Attachment',
    concepts: ['modes-of-nature', 'attachment', 'action'],
    reviewed: false,
  },
  '3.29': {
    theme: 'Modes Of Nature & Knowledge',
    concepts: ['modes-of-nature', 'knowledge', 'illusion', 'attachment'],
    reviewed: false,
  },
  '3.30': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '3.31': {
    theme: 'Faith & Bondage',
    concepts: ['faith', 'bondage'],
    reviewed: false,
  },
  '3.32': {
    theme: 'Knowledge & Wisdom',
    concepts: ['knowledge', 'wisdom', 'illusion'],
    reviewed: false,
  },
  '3.33': {
    theme: 'Wisdom & Knowledge',
    concepts: ['wisdom', 'knowledge', 'modes-of-nature'],
    reviewed: false,
  },
  '3.34': {
    theme: 'Attachment',
    concepts: ['attachment'],
    reviewed: false,
  },
  '3.37': {
    theme: 'Modes Of Nature & Desire',
    concepts: ['modes-of-nature', 'desire', 'anger', 'supreme-person'],
    reviewed: false,
  },
  '3.38': {
    theme: 'Desire',
    concepts: ['desire'],
    reviewed: false,
  },
  '3.39': {
    theme: 'Wisdom & Desire',
    concepts: ['wisdom', 'desire', 'knowledge', 'war'],
    reviewed: false,
  },
  '3.40': {
    theme: 'Soul & Wisdom',
    concepts: ['soul', 'wisdom'],
    reviewed: false,
  },
  '3.41': {
    theme: 'Knowledge & Self Realization',
    concepts: ['knowledge', 'self-realization'],
    reviewed: false,
  },
  '3.42': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '3.43': {
    theme: 'Desire & Soul',
    concepts: ['desire', 'soul', 'war', 'discipline'],
    reviewed: false,
  },
  '4.1': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '4.3': {
    theme: 'Devotion & Supreme Person',
    concepts: ['devotion', 'supreme-person'],
    reviewed: false,
  },
  '4.5': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '4.6': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '4.8': {
    theme: 'Dharma & Grace',
    concepts: ['dharma', 'grace'],
    reviewed: false,
  },
  '4.10': {
    theme: 'Knowledge & Anger',
    concepts: ['knowledge', 'anger', 'purity', 'attachment'],
    reviewed: false,
  },
  '4.12': {
    theme: 'Action',
    concepts: ['action'],
    reviewed: false,
  },
  '4.13': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '4.14': {
    theme: 'Desire & Action',
    concepts: ['desire', 'action', 'bondage'],
    reviewed: false,
  },
  '4.15': {
    theme: 'Action & Liberation',
    concepts: ['action', 'liberation', 'wisdom'],
    reviewed: false,
  },
  '4.16': {
    theme: 'Wisdom & Action',
    concepts: ['wisdom', 'action', 'illusion', 'knowledge'],
    reviewed: false,
  },
  '4.17': {
    theme: 'Action & Knowledge',
    concepts: ['action', 'knowledge'],
    reviewed: false,
  },
  '4.19': {
    theme: 'Wisdom & Knowledge',
    concepts: ['wisdom', 'knowledge', 'desire'],
    reviewed: false,
  },
  '4.20': {
    theme: 'Action & Attachment',
    concepts: ['action', 'attachment'],
    reviewed: false,
  },
  '4.22': {
    theme: 'Bondage & Equanimity',
    concepts: ['bondage', 'equanimity'],
    reviewed: false,
  },
  '4.23': {
    theme: 'Knowledge & Sacrifice',
    concepts: ['knowledge', 'sacrifice', 'liberation', 'attachment'],
    reviewed: false,
  },
  '4.24': {
    theme: 'Sacrifice & Action',
    concepts: ['sacrifice', 'action', 'soul', 'supreme-person'],
    reviewed: false,
  },
  '4.25': {
    theme: 'Sacrifice & Soul',
    concepts: ['sacrifice', 'soul'],
    reviewed: false,
  },
  '4.26': {
    theme: 'Sacrifice & Discipline',
    concepts: ['sacrifice', 'discipline'],
    reviewed: false,
  },
  '4.27': {
    theme: 'Knowledge & Sacrifice',
    concepts: ['knowledge', 'sacrifice', 'soul'],
    reviewed: false,
  },
  '4.28': {
    theme: 'Sacrifice & Knowledge',
    concepts: ['sacrifice', 'knowledge', 'austerity', 'meditation'],
    reviewed: false,
  },
  '4.29': {
    theme: 'Sacrifice & Discipline',
    concepts: ['sacrifice', 'discipline'],
    reviewed: false,
  },
  '4.30': {
    theme: 'Sacrifice',
    concepts: ['sacrifice'],
    reviewed: false,
  },
  '4.31': {
    theme: 'Sacrifice & Soul',
    concepts: ['sacrifice', 'soul'],
    reviewed: false,
  },
  '4.32': {
    theme: 'Sacrifice & Liberation',
    concepts: ['sacrifice', 'liberation', 'action', 'knowledge'],
    reviewed: false,
  },
  '4.33': {
    theme: 'Knowledge & Sacrifice',
    concepts: ['knowledge', 'sacrifice', 'wisdom'],
    reviewed: false,
  },
  '4.34': {
    theme: 'Knowledge & Wisdom',
    concepts: ['knowledge', 'wisdom', 'self-realization'],
    reviewed: false,
  },
  '4.35': {
    theme: 'Illusion',
    concepts: ['illusion'],
    reviewed: false,
  },
  '4.36': {
    theme: 'Knowledge',
    concepts: ['knowledge'],
    reviewed: false,
  },
  '4.37': {
    theme: 'Knowledge',
    concepts: ['knowledge'],
    reviewed: false,
  },
  '4.39': {
    theme: 'Faith & Knowledge',
    concepts: ['faith', 'knowledge', 'devotion', 'equanimity'],
    reviewed: false,
  },
  '4.40': {
    theme: 'Faith & Soul',
    concepts: ['faith', 'soul', 'illusion'],
    reviewed: false,
  },
  '4.41': {
    theme: 'Knowledge & Soul',
    concepts: ['knowledge', 'soul', 'renunciation', 'bondage'],
    reviewed: false,
  },
  '4.42': {
    theme: 'Knowledge & Surrender',
    concepts: ['knowledge', 'surrender', 'illusion', 'soul'],
    reviewed: false,
  },
  '5.1': {
    theme: 'Renunciation',
    concepts: ['renunciation'],
    reviewed: false,
  },
  '5.2': {
    theme: 'Action & Renunciation',
    concepts: ['action', 'renunciation', 'supreme-person', 'devotion'],
    reviewed: false,
  },
  '5.3': {
    theme: 'Bondage & Renunciation',
    concepts: ['bondage', 'renunciation', 'liberation'],
    reviewed: false,
  },
  '5.4': {
    theme: 'Wisdom & Action',
    concepts: ['wisdom', 'action', 'knowledge'],
    reviewed: false,
  },
  '5.5': {
    theme: 'Action',
    concepts: ['action'],
    reviewed: false,
  },
  '5.6': {
    theme: 'Renunciation & Meditation',
    concepts: ['renunciation', 'meditation', 'wisdom'],
    reviewed: false,
  },
  '5.7': {
    theme: 'Soul & Unity',
    concepts: ['soul', 'unity', 'purity'],
    reviewed: false,
  },
  '5.11': {
    theme: 'Attachment & Soul',
    concepts: ['attachment', 'soul', 'action'],
    reviewed: false,
  },
  '5.12': {
    theme: 'Desire & Unity',
    concepts: ['desire', 'unity', 'attachment', 'equanimity'],
    reviewed: false,
  },
  '5.13': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '5.14': {
    theme: 'Action',
    concepts: ['action'],
    reviewed: false,
  },
  '5.15': {
    theme: 'Illusion & Knowledge',
    concepts: ['illusion', 'knowledge'],
    reviewed: false,
  },
  '5.16': {
    theme: 'Knowledge & Supreme Person',
    concepts: ['knowledge', 'supreme-person', 'illusion', 'soul'],
    reviewed: false,
  },
  '5.17': {
    theme: 'Knowledge & Faith',
    concepts: ['knowledge', 'faith'],
    reviewed: false,
  },
  '5.19': {
    theme: 'Supreme Person & Equanimity',
    concepts: ['supreme-person', 'equanimity'],
    reviewed: false,
  },
  '5.20': {
    theme: 'Knowledge',
    concepts: ['knowledge'],
    reviewed: false,
  },
  '5.21': {
    theme: 'Soul & Detachment',
    concepts: ['soul', 'detachment'],
    reviewed: false,
  },
  '5.22': {
    theme: 'Wisdom',
    concepts: ['wisdom'],
    reviewed: false,
  },
  '5.23': {
    theme: 'Anger & Desire',
    concepts: ['anger', 'desire'],
    reviewed: false,
  },
  '5.24': {
    theme: 'Liberation & Soul',
    concepts: ['liberation', 'soul', 'meditation'],
    reviewed: false,
  },
  '5.25': {
    theme: 'Liberation & Soul',
    concepts: ['liberation', 'soul'],
    reviewed: false,
  },
  '5.26': {
    theme: 'Anger & Self Realization',
    concepts: ['anger', 'self-realization', 'desire', 'liberation'],
    reviewed: false,
  },
  '5.27': {
    theme: 'Liberation',
    concepts: ['liberation'],
    reviewed: false,
  },
  '5.28': {
    theme: 'Liberation & Anger',
    concepts: ['liberation', 'anger', 'desire', 'wisdom'],
    reviewed: false,
  },
  '5.29': {
    theme: 'Sacrifice & Austerity',
    concepts: ['sacrifice', 'austerity', 'equanimity', 'supreme-person'],
    reviewed: false,
  },
  '6.1': {
    theme: 'Action & Duty',
    concepts: ['action', 'duty', 'meditation', 'renunciation'],
    reviewed: false,
  },
  '6.2': {
    theme: 'Renunciation & Meditation',
    concepts: ['renunciation', 'meditation'],
    reviewed: false,
  },
  '6.3': {
    theme: 'Meditation & Discipline',
    concepts: ['meditation', 'discipline', 'wisdom'],
    reviewed: false,
  },
  '6.4': {
    theme: 'Attachment',
    concepts: ['attachment'],
    reviewed: false,
  },
  '6.6': {
    theme: 'Soul & War',
    concepts: ['soul', 'war'],
    reviewed: false,
  },
  '6.7': {
    theme: 'Equanimity & Soul',
    concepts: ['equanimity', 'soul'],
    reviewed: false,
  },
  '6.8': {
    theme: 'Knowledge & Wisdom',
    concepts: ['knowledge', 'wisdom', 'equanimity', 'meditation'],
    reviewed: false,
  },
  '6.10': {
    theme: 'Meditation & Desire',
    concepts: ['meditation', 'desire'],
    reviewed: false,
  },
  '6.14': {
    theme: 'Equanimity',
    concepts: ['equanimity'],
    reviewed: false,
  },
  '6.15': {
    theme: 'Liberation & Equanimity',
    concepts: ['liberation', 'equanimity', 'meditation'],
    reviewed: false,
  },
  '6.18': {
    theme: 'Soul & Desire',
    concepts: ['soul', 'desire'],
    reviewed: false,
  },
  '6.19': {
    theme: 'Meditation',
    concepts: ['meditation'],
    reviewed: false,
  },
  '6.20': {
    theme: 'Soul & Unity',
    concepts: ['soul', 'unity'],
    reviewed: false,
  },
  '6.22': {
    theme: 'Grief',
    concepts: ['grief'],
    reviewed: false,
  },
  '6.23': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '6.25': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '6.26': {
    theme: 'Discipline',
    concepts: ['discipline'],
    reviewed: false,
  },
  '6.27': {
    theme: 'Equanimity & Supreme Person',
    concepts: ['equanimity', 'supreme-person'],
    reviewed: false,
  },
  '6.28': {
    theme: 'Soul & Meditation',
    concepts: ['soul', 'meditation'],
    reviewed: false,
  },
  '6.29': {
    theme: 'Unity & Soul',
    concepts: ['unity', 'soul'],
    reviewed: false,
  },
  '6.30': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '6.31': {
    theme: 'Unity & Meditation',
    concepts: ['unity', 'meditation'],
    reviewed: false,
  },
  '6.32': {
    theme: 'Meditation & Soul',
    concepts: ['meditation', 'soul', 'unity'],
    reviewed: false,
  },
  '6.33': {
    theme: 'Equanimity',
    concepts: ['equanimity'],
    reviewed: false,
  },
  '6.34': {
    theme: 'Discipline',
    concepts: ['discipline'],
    reviewed: false,
  },
  '6.36': {
    theme: 'Self Realization & Soul',
    concepts: ['self-realization', 'soul'],
    reviewed: false,
  },
  '6.37': {
    theme: 'Faith & Self Realization',
    concepts: ['faith', 'self-realization'],
    reviewed: false,
  },
  '6.38': {
    theme: 'Illusion',
    concepts: ['illusion'],
    reviewed: false,
  },
  '6.39': {
    theme: 'Faith',
    concepts: ['faith'],
    reviewed: false,
  },
  '6.40': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '6.41': {
    theme: 'Dharma',
    concepts: ['dharma'],
    reviewed: false,
  },
  '6.42': {
    theme: 'Wisdom',
    concepts: ['wisdom'],
    reviewed: false,
  },
  '6.43': {
    theme: 'Self Realization & Wisdom',
    concepts: ['self-realization', 'wisdom'],
    reviewed: false,
  },
  '6.44': {
    theme: 'Transcendence',
    concepts: ['transcendence'],
    reviewed: false,
  },
  '6.45': {
    theme: 'Meditation & Purity',
    concepts: ['meditation', 'purity'],
    reviewed: false,
  },
  '6.46': {
    theme: 'Meditation & Wisdom',
    concepts: ['meditation', 'wisdom', 'knowledge'],
    reviewed: false,
  },
  '6.47': {
    theme: 'Faith & Devotion',
    concepts: ['faith', 'devotion'],
    reviewed: false,
  },
  '7.1': {
    theme: 'Devotion & Surrender',
    concepts: ['devotion', 'surrender', 'supreme-person'],
    reviewed: false,
  },
  '7.2': {
    theme: 'Knowledge & Self Realization',
    concepts: ['knowledge', 'self-realization'],
    reviewed: false,
  },
  '7.3': {
    theme: 'Self Realization',
    concepts: ['self-realization'],
    reviewed: false,
  },
  '7.4': {
    theme: 'Ego',
    concepts: ['ego'],
    reviewed: false,
  },
  '7.5': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '7.6': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '7.9': {
    theme: 'Unity & Austerity',
    concepts: ['unity', 'austerity'],
    reviewed: false,
  },
  '7.10': {
    theme: 'Wisdom & Opulence',
    concepts: ['wisdom', 'opulence', 'soul'],
    reviewed: false,
  },
  '7.11': {
    theme: 'Desire & Dharma',
    concepts: ['desire', 'dharma', 'unity', 'attachment'],
    reviewed: false,
  },
  '7.12': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '7.13': {
    theme: 'Modes Of Nature & Illusion',
    concepts: ['modes-of-nature', 'illusion'],
    reviewed: false,
  },
  '7.15': {
    theme: 'Illusion & Surrender',
    concepts: ['illusion', 'surrender'],
    reviewed: false,
  },
  '7.16': {
    theme: 'Knowledge & Devotion',
    concepts: ['knowledge', 'devotion', 'wisdom'],
    reviewed: false,
  },
  '7.17': {
    theme: 'Wisdom & Knowledge',
    concepts: ['wisdom', 'knowledge', 'devotion'],
    reviewed: false,
  },
  '7.18': {
    theme: 'Soul & Wisdom',
    concepts: ['soul', 'wisdom', 'knowledge'],
    reviewed: false,
  },
  '7.19': {
    theme: 'Soul & Knowledge',
    concepts: ['soul', 'knowledge', 'wisdom'],
    reviewed: false,
  },
  '7.20': {
    theme: 'Desire & Wisdom',
    concepts: ['desire', 'wisdom'],
    reviewed: false,
  },
  '7.21': {
    theme: 'Devotion & Faith',
    concepts: ['devotion', 'faith'],
    reviewed: false,
  },
  '7.22': {
    theme: 'Faith',
    concepts: ['faith'],
    reviewed: false,
  },
  '7.24': {
    theme: 'Remembrance & Knowledge',
    concepts: ['remembrance', 'knowledge', 'soul'],
    reviewed: false,
  },
  '7.25': {
    theme: 'Illusion & Soul',
    concepts: ['illusion', 'soul', 'supreme-person'],
    reviewed: false,
  },
  '7.26': {
    theme: 'Knowledge',
    concepts: ['knowledge'],
    reviewed: false,
  },
  '7.27': {
    theme: 'Illusion & Desire',
    concepts: ['illusion', 'desire'],
    reviewed: false,
  },
  '7.28': {
    theme: 'Devotion & Illusion',
    concepts: ['devotion', 'illusion'],
    reviewed: false,
  },
  '7.29': {
    theme: 'Death & Liberation',
    concepts: ['death', 'liberation', 'surrender', 'soul'],
    reviewed: false,
  },
  '7.30': {
    theme: 'Death & Sacrifice',
    concepts: ['death', 'sacrifice'],
    reviewed: false,
  },
  '8.1': {
    theme: 'Supreme Person & Soul',
    concepts: ['supreme-person', 'soul'],
    reviewed: false,
  },
  '8.2': {
    theme: 'Death & Remembrance',
    concepts: ['death', 'remembrance', 'soul', 'discipline'],
    reviewed: false,
  },
  '8.3': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '8.4': {
    theme: 'Soul & Impermanence',
    concepts: ['soul', 'impermanence', 'sacrifice'],
    reviewed: false,
  },
  '8.6': {
    theme: 'Remembrance',
    concepts: ['remembrance'],
    reviewed: false,
  },
  '8.7': {
    theme: 'War & Surrender',
    concepts: ['war', 'surrender', 'remembrance'],
    reviewed: false,
  },
  '8.8': {
    theme: 'Meditation & Supreme Person',
    concepts: ['meditation', 'supreme-person', 'remembrance'],
    reviewed: false,
  },
  '8.9': {
    theme: 'Transcendence & Universal Form',
    concepts: ['transcendence', 'universal-form'],
    reviewed: false,
  },
  '8.10': {
    theme: 'Supreme Person & Devotion',
    concepts: ['supreme-person', 'devotion', 'remembrance', 'death'],
    reviewed: false,
  },
  '8.11': {
    theme: 'Soul & Modes Of Nature',
    concepts: ['soul', 'modes-of-nature'],
    reviewed: false,
  },
  '8.12': {
    theme: 'Meditation',
    concepts: ['meditation'],
    reviewed: false,
  },
  '8.13': {
    theme: 'Remembrance & Supreme Person',
    concepts: ['remembrance', 'supreme-person'],
    reviewed: false,
  },
  '8.14': {
    theme: 'Remembrance',
    concepts: ['remembrance'],
    reviewed: false,
  },
  '8.15': {
    theme: 'Self Realization',
    concepts: ['self-realization'],
    reviewed: false,
  },
  '8.17': {
    theme: 'Universal Form & Knowledge',
    concepts: ['universal-form', 'knowledge'],
    reviewed: false,
  },
  '8.20': {
    theme: 'Soul & Transcendence',
    concepts: ['soul', 'transcendence'],
    reviewed: false,
  },
  '8.21': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '8.22': {
    theme: 'Devotion & Unity',
    concepts: ['devotion', 'unity'],
    reviewed: false,
  },
  '8.24': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '8.25': {
    theme: 'Meditation',
    concepts: ['meditation'],
    reviewed: false,
  },
  '8.27': {
    theme: 'Meditation & Illusion',
    concepts: ['meditation', 'illusion'],
    reviewed: false,
  },
  '8.28': {
    theme: 'Austerity & Sacrifice',
    concepts: ['austerity', 'sacrifice', 'meditation', 'supreme-person'],
    reviewed: false,
  },
  '9.1': {
    theme: 'Knowledge & Supreme Person',
    concepts: ['knowledge', 'supreme-person'],
    reviewed: false,
  },
  '9.2': {
    theme: 'Dharma & Supreme Person',
    concepts: ['dharma', 'supreme-person'],
    reviewed: false,
  },
  '9.3': {
    theme: 'Faith & Dharma',
    concepts: ['faith', 'dharma'],
    reviewed: false,
  },
  '9.4': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '9.5': {
    theme: 'Soul & Unity',
    concepts: ['soul', 'unity'],
    reviewed: false,
  },
  '9.6': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '9.9': {
    theme: 'Detachment & Bondage',
    concepts: ['detachment', 'bondage'],
    reviewed: false,
  },
  '9.11': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '9.12': {
    theme: 'Knowledge & Illusion',
    concepts: ['knowledge', 'illusion'],
    reviewed: false,
  },
  '9.13': {
    theme: 'Soul & Devotion',
    concepts: ['soul', 'devotion'],
    reviewed: false,
  },
  '9.14': {
    theme: 'Devotion',
    concepts: ['devotion'],
    reviewed: false,
  },
  '9.15': {
    theme: 'Devotion & Knowledge',
    concepts: ['devotion', 'knowledge', 'sacrifice', 'unity'],
    reviewed: false,
  },
  '9.16': {
    theme: 'Sacrifice',
    concepts: ['sacrifice'],
    reviewed: false,
  },
  '9.18': {
    theme: 'Soul & Surrender',
    concepts: ['soul', 'surrender', 'supreme-person'],
    reviewed: false,
  },
  '9.19': {
    theme: 'Death',
    concepts: ['death'],
    reviewed: false,
  },
  '9.20': {
    theme: 'Purity & Sacrifice',
    concepts: ['purity', 'sacrifice'],
    reviewed: false,
  },
  '9.23': {
    theme: 'Devotion & Faith',
    concepts: ['devotion', 'faith'],
    reviewed: false,
  },
  '9.24': {
    theme: 'Sacrifice & Supreme Person',
    concepts: ['sacrifice', 'supreme-person'],
    reviewed: false,
  },
  '9.26': {
    theme: 'Devotion & Purity',
    concepts: ['devotion', 'purity'],
    reviewed: false,
  },
  '9.28': {
    theme: 'Renunciation & Liberation',
    concepts: ['renunciation', 'liberation', 'action'],
    reviewed: false,
  },
  '9.29': {
    theme: 'Devotion & Unity',
    concepts: ['devotion', 'unity'],
    reviewed: false,
  },
  '9.30': {
    theme: 'Dharma & Devotion',
    concepts: ['dharma', 'devotion'],
    reviewed: false,
  },
  '9.31': {
    theme: 'Devotion & Dharma',
    concepts: ['devotion', 'dharma', 'equanimity', 'soul'],
    reviewed: false,
  },
  '9.32': {
    theme: 'Surrender',
    concepts: ['surrender'],
    reviewed: false,
  },
  '9.33': {
    theme: 'Devotion & Impermanence',
    concepts: ['devotion', 'impermanence'],
    reviewed: false,
  },
  '9.34': {
    theme: 'Sacrifice & Devotion',
    concepts: ['sacrifice', 'devotion', 'unity', 'surrender'],
    reviewed: false,
  },
  '10.1': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '10.2': {
    theme: 'Wisdom & Supreme Person',
    concepts: ['wisdom', 'supreme-person'],
    reviewed: false,
  },
  '10.3': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '10.4': {
    theme: 'Discipline & Death',
    concepts: ['discipline', 'death', 'wisdom', 'grief'],
    reviewed: false,
  },
  '10.5': {
    theme: 'Austerity & Compassion',
    concepts: ['austerity', 'compassion', 'equanimity'],
    reviewed: false,
  },
  '10.7': {
    theme: 'Faith & Opulence',
    concepts: ['faith', 'opulence'],
    reviewed: false,
  },
  '10.8': {
    theme: 'Devotion & Wisdom',
    concepts: ['devotion', 'wisdom', 'supreme-person', 'knowledge'],
    reviewed: false,
  },
  '10.10': {
    theme: 'Devotion & Wisdom',
    concepts: ['devotion', 'wisdom'],
    reviewed: false,
  },
  '10.11': {
    theme: 'Knowledge & Compassion',
    concepts: ['knowledge', 'compassion', 'illusion'],
    reviewed: false,
  },
  '10.12': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '10.13': {
    theme: 'Wisdom',
    concepts: ['wisdom'],
    reviewed: false,
  },
  '10.14': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '10.15': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '10.16': {
    theme: 'Unity & Opulence',
    concepts: ['unity', 'opulence'],
    reviewed: false,
  },
  '10.17': {
    theme: 'Meditation & Supreme Person',
    concepts: ['meditation', 'supreme-person'],
    reviewed: false,
  },
  '10.18': {
    theme: 'Opulence',
    concepts: ['opulence'],
    reviewed: false,
  },
  '10.19': {
    theme: 'Opulence',
    concepts: ['opulence'],
    reviewed: false,
  },
  '10.23': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '10.24': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '10.25': {
    theme: 'Sacrifice',
    concepts: ['sacrifice'],
    reviewed: false,
  },
  '10.26': {
    theme: 'Wisdom',
    concepts: ['wisdom'],
    reviewed: false,
  },
  '10.29': {
    theme: 'Death',
    concepts: ['death'],
    reviewed: false,
  },
  '10.33': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '10.34': {
    theme: 'Death & Supreme Person',
    concepts: ['death', 'supreme-person'],
    reviewed: false,
  },
  '10.36': {
    theme: 'Opulence & War',
    concepts: ['opulence', 'war', 'modes-of-nature', 'purity'],
    reviewed: false,
  },
  '10.37': {
    theme: 'Wisdom',
    concepts: ['wisdom'],
    reviewed: false,
  },
  '10.38': {
    theme: 'Wisdom & Knowledge',
    concepts: ['wisdom', 'knowledge'],
    reviewed: false,
  },
  '10.40': {
    theme: 'Opulence',
    concepts: ['opulence'],
    reviewed: false,
  },
  '10.41': {
    theme: 'Opulence',
    concepts: ['opulence'],
    reviewed: false,
  },
  '10.42': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '11.1': {
    theme: 'Illusion & Supreme Person',
    concepts: ['illusion', 'supreme-person'],
    reviewed: false,
  },
  '11.3': {
    theme: 'Supreme Person & Universal Form',
    concepts: ['supreme-person', 'universal-form'],
    reviewed: false,
  },
  '11.4': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '11.5': {
    theme: 'Universal Form & Supreme Person',
    concepts: ['universal-form', 'supreme-person'],
    reviewed: false,
  },
  '11.6': {
    theme: 'Universal Form',
    concepts: ['universal-form'],
    reviewed: false,
  },
  '11.7': {
    theme: 'Universal Form',
    concepts: ['universal-form'],
    reviewed: false,
  },
  '11.8': {
    theme: 'Universal Form & Opulence',
    concepts: ['universal-form', 'opulence'],
    reviewed: false,
  },
  '11.9': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '11.12': {
    theme: 'Opulence & Universal Form',
    concepts: ['opulence', 'universal-form'],
    reviewed: false,
  },
  '11.15': {
    theme: 'Supreme Person & Wisdom',
    concepts: ['supreme-person', 'wisdom'],
    reviewed: false,
  },
  '11.16': {
    theme: 'Universal Form',
    concepts: ['universal-form'],
    reviewed: false,
  },
  '11.17': {
    theme: 'Universal Form & Opulence',
    concepts: ['universal-form', 'opulence', 'unity'],
    reviewed: false,
  },
  '11.18': {
    theme: 'Soul & Dharma',
    concepts: ['soul', 'dharma', 'supreme-person'],
    reviewed: false,
  },
  '11.20': {
    theme: 'Universal Form',
    concepts: ['universal-form'],
    reviewed: false,
  },
  '11.23': {
    theme: 'Universal Form',
    concepts: ['universal-form'],
    reviewed: false,
  },
  '11.24': {
    theme: 'Equanimity & Universal Form',
    concepts: ['equanimity', 'universal-form'],
    reviewed: false,
  },
  '11.25': {
    theme: 'Compassion & Universal Form',
    concepts: ['compassion', 'universal-form'],
    reviewed: false,
  },
  '11.27': {
    theme: 'Universal Form',
    concepts: ['universal-form'],
    reviewed: false,
  },
  '11.31': {
    theme: 'Compassion',
    concepts: ['compassion'],
    reviewed: false,
  },
  '11.32': {
    theme: 'War & Supreme Person',
    concepts: ['war', 'supreme-person'],
    reviewed: false,
  },
  '11.34': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '11.37': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '11.38': {
    theme: 'Knowledge & Liberation',
    concepts: ['knowledge', 'liberation', 'supreme-person'],
    reviewed: false,
  },
  '11.39': {
    theme: 'Sacrifice & Death',
    concepts: ['sacrifice', 'death', 'universal-form'],
    reviewed: false,
  },
  '11.40': {
    theme: 'Unity & Sacrifice',
    concepts: ['unity', 'sacrifice'],
    reviewed: false,
  },
  '11.41': {
    theme: 'Illusion',
    concepts: ['illusion'],
    reviewed: false,
  },
  '11.43': {
    theme: 'Equanimity & Guru',
    concepts: ['equanimity', 'guru'],
    reviewed: false,
  },
  '11.44': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '11.45': {
    theme: 'Compassion & Supreme Person',
    concepts: ['compassion', 'supreme-person'],
    reviewed: false,
  },
  '11.46': {
    theme: 'Universal Form',
    concepts: ['universal-form'],
    reviewed: false,
  },
  '11.47': {
    theme: 'Universal Form & Opulence',
    concepts: ['universal-form', 'opulence'],
    reviewed: false,
  },
  '11.48': {
    theme: 'Sacrifice & Austerity',
    concepts: ['sacrifice', 'austerity', 'charity'],
    reviewed: false,
  },
  '11.49': {
    theme: 'Universal Form & Illusion',
    concepts: ['universal-form', 'illusion'],
    reviewed: false,
  },
  '11.50': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '11.52': {
    theme: 'Universal Form & Supreme Person',
    concepts: ['universal-form', 'supreme-person'],
    reviewed: false,
  },
  '11.53': {
    theme: 'Charity & Austerity',
    concepts: ['charity', 'austerity', 'sacrifice'],
    reviewed: false,
  },
  '11.55': {
    theme: 'Attachment & Detachment',
    concepts: ['attachment', 'detachment', 'devotion', 'supreme-person'],
    reviewed: false,
  },
  '12.1': {
    theme: 'Devotion & Soul',
    concepts: ['devotion', 'soul'],
    reviewed: false,
  },
  '12.2': {
    theme: 'Faith & Devotion',
    concepts: ['faith', 'devotion', 'supreme-person'],
    reviewed: false,
  },
  '12.3': {
    theme: 'Soul & Unity',
    concepts: ['soul', 'unity', 'devotion'],
    reviewed: false,
  },
  '12.4': {
    theme: 'Unity & Equanimity',
    concepts: ['unity', 'equanimity'],
    reviewed: false,
  },
  '12.6': {
    theme: 'Meditation & Devotion',
    concepts: ['meditation', 'devotion'],
    reviewed: false,
  },
  '12.7': {
    theme: 'Death',
    concepts: ['death'],
    reviewed: false,
  },
  '12.10': {
    theme: 'Action',
    concepts: ['action'],
    reviewed: false,
  },
  '12.11': {
    theme: 'Discipline & Renunciation',
    concepts: ['discipline', 'renunciation', 'soul', 'surrender'],
    reviewed: false,
  },
  '12.12': {
    theme: 'Knowledge & Meditation',
    concepts: ['knowledge', 'meditation', 'renunciation', 'equanimity'],
    reviewed: false,
  },
  '12.14': {
    theme: 'Devotion & Soul',
    concepts: ['devotion', 'soul', 'meditation'],
    reviewed: false,
  },
  '12.15': {
    theme: 'Grief & Anger',
    concepts: ['grief', 'anger'],
    reviewed: false,
  },
  '12.16': {
    theme: 'Devotion & Purity',
    concepts: ['devotion', 'purity'],
    reviewed: false,
  },
  '12.17': {
    theme: 'Devotion & Grief',
    concepts: ['devotion', 'grief'],
    reviewed: false,
  },
  '12.18': {
    theme: 'Equanimity & Attachment',
    concepts: ['equanimity', 'attachment'],
    reviewed: false,
  },
  '12.19': {
    theme: 'Devotion & Detachment',
    concepts: ['devotion', 'detachment'],
    reviewed: false,
  },
  '12.20': {
    theme: 'Faith & Dharma',
    concepts: ['faith', 'dharma', 'wisdom', 'devotion'],
    reviewed: false,
  },
  '13.1': {
    theme: 'Knowledge & Modes Of Nature',
    concepts: ['knowledge', 'modes-of-nature'],
    reviewed: false,
  },
  '13.2': {
    theme: 'Supreme Person & Wisdom',
    concepts: ['supreme-person', 'wisdom'],
    reviewed: false,
  },
  '13.3': {
    theme: 'Knowledge',
    concepts: ['knowledge'],
    reviewed: false,
  },
  '13.6': {
    theme: 'Ego',
    concepts: ['ego'],
    reviewed: false,
  },
  '13.7': {
    theme: 'Desire',
    concepts: ['desire'],
    reviewed: false,
  },
  '13.9': {
    theme: 'Death & Ego',
    concepts: ['death', 'ego'],
    reviewed: false,
  },
  '13.10': {
    theme: 'Attachment',
    concepts: ['attachment'],
    reviewed: false,
  },
  '13.11': {
    theme: 'Devotion',
    concepts: ['devotion'],
    reviewed: false,
  },
  '13.12': {
    theme: 'Knowledge & Illusion',
    concepts: ['knowledge', 'illusion'],
    reviewed: false,
  },
  '13.13': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '13.14': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '13.15': {
    theme: 'Modes Of Nature & Detachment',
    concepts: ['modes-of-nature', 'detachment'],
    reviewed: false,
  },
  '13.17': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '13.18': {
    theme: 'Knowledge & Transcendence',
    concepts: ['knowledge', 'transcendence', 'wisdom'],
    reviewed: false,
  },
  '13.19': {
    theme: 'Knowledge & Devotion',
    concepts: ['knowledge', 'devotion'],
    reviewed: false,
  },
  '13.20': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '13.21': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '13.22': {
    theme: 'Modes Of Nature & Attachment',
    concepts: ['modes-of-nature', 'attachment', 'soul'],
    reviewed: false,
  },
  '13.23': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '13.24': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '13.25': {
    theme: 'Meditation & Action',
    concepts: ['meditation', 'action', 'soul', 'knowledge'],
    reviewed: false,
  },
  '13.26': {
    theme: 'Death & Devotion',
    concepts: ['death', 'devotion'],
    reviewed: false,
  },
  '13.28': {
    theme: 'Soul & Unity',
    concepts: ['soul', 'unity', 'impermanence', 'supreme-person'],
    reviewed: false,
  },
  '13.29': {
    theme: 'Soul & Equanimity',
    concepts: ['soul', 'equanimity', 'unity', 'supreme-person'],
    reviewed: false,
  },
  '13.30': {
    theme: 'Soul & Modes Of Nature',
    concepts: ['soul', 'modes-of-nature'],
    reviewed: false,
  },
  '13.31': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '13.32': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '13.33': {
    theme: 'Unity & Soul',
    concepts: ['unity', 'soul'],
    reviewed: false,
  },
  '13.34': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '13.35': {
    theme: 'Knowledge & Modes Of Nature',
    concepts: ['knowledge', 'modes-of-nature', 'supreme-person', 'liberation'],
    reviewed: false,
  },
  '14.1': {
    theme: 'Knowledge & Wisdom',
    concepts: ['knowledge', 'wisdom', 'supreme-person', 'self-realization'],
    reviewed: false,
  },
  '14.2': {
    theme: 'Surrender & Wisdom',
    concepts: ['surrender', 'wisdom'],
    reviewed: false,
  },
  '14.5': {
    theme: 'Modes Of Nature & Soul',
    concepts: ['modes-of-nature', 'soul', 'bondage', 'purity'],
    reviewed: false,
  },
  '14.6': {
    theme: 'Purity & Attachment',
    concepts: ['purity', 'attachment', 'knowledge', 'modes-of-nature'],
    reviewed: false,
  },
  '14.7': {
    theme: 'Modes Of Nature & Attachment',
    concepts: ['modes-of-nature', 'attachment', 'soul'],
    reviewed: false,
  },
  '14.8': {
    theme: 'Illusion & Modes Of Nature',
    concepts: ['illusion', 'modes-of-nature', 'soul'],
    reviewed: false,
  },
  '14.9': {
    theme: 'Modes Of Nature & Illusion',
    concepts: ['modes-of-nature', 'illusion', 'wisdom'],
    reviewed: false,
  },
  '14.10': {
    theme: 'Modes Of Nature & Purity',
    concepts: ['modes-of-nature', 'purity', 'illusion'],
    reviewed: false,
  },
  '14.11': {
    theme: 'Modes Of Nature & Knowledge',
    concepts: ['modes-of-nature', 'knowledge'],
    reviewed: false,
  },
  '14.12': {
    theme: 'Modes Of Nature & Desire',
    concepts: ['modes-of-nature', 'desire', 'action'],
    reviewed: false,
  },
  '14.13': {
    theme: 'Illusion & Modes Of Nature',
    concepts: ['illusion', 'modes-of-nature'],
    reviewed: false,
  },
  '14.14': {
    theme: 'Purity & Modes Of Nature',
    concepts: ['purity', 'modes-of-nature', 'soul', 'death'],
    reviewed: false,
  },
  '14.15': {
    theme: 'Modes Of Nature & Death',
    concepts: ['modes-of-nature', 'death', 'action', 'illusion'],
    reviewed: false,
  },
  '14.16': {
    theme: 'Modes Of Nature & Purity',
    concepts: ['modes-of-nature', 'purity', 'action', 'illusion'],
    reviewed: false,
  },
  '14.17': {
    theme: 'Modes Of Nature & Illusion',
    concepts: ['modes-of-nature', 'illusion', 'knowledge'],
    reviewed: false,
  },
  '14.18': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '14.19': {
    theme: 'Modes Of Nature & Purity',
    concepts: ['modes-of-nature', 'purity'],
    reviewed: false,
  },
  '14.20': {
    theme: 'Death & Modes Of Nature',
    concepts: ['death', 'modes-of-nature', 'soul', 'transcendence'],
    reviewed: false,
  },
  '14.21': {
    theme: 'Modes Of Nature & Transcendence',
    concepts: ['modes-of-nature', 'transcendence'],
    reviewed: false,
  },
  '14.23': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '14.24': {
    theme: 'Equanimity & Soul',
    concepts: ['equanimity', 'soul'],
    reviewed: false,
  },
  '14.25': {
    theme: 'Equanimity & Modes Of Nature',
    concepts: ['equanimity', 'modes-of-nature'],
    reviewed: false,
  },
  '14.26': {
    theme: 'Devotion & Modes Of Nature',
    concepts: ['devotion', 'modes-of-nature', 'transcendence'],
    reviewed: false,
  },
  '14.27': {
    theme: 'Soul & Dharma',
    concepts: ['soul', 'dharma', 'supreme-person'],
    reviewed: false,
  },
  '15.1': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '15.2': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '15.3': {
    theme: 'Attachment',
    concepts: ['attachment'],
    reviewed: false,
  },
  '15.4': {
    theme: 'Surrender',
    concepts: ['surrender'],
    reviewed: false,
  },
  '15.5': {
    theme: 'Soul & Ego',
    concepts: ['soul', 'ego', 'illusion', 'attachment'],
    reviewed: false,
  },
  '15.8': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person'],
    reviewed: false,
  },
  '15.10': {
    theme: 'Knowledge & Modes Of Nature',
    concepts: ['knowledge', 'modes-of-nature', 'illusion', 'universal-form'],
    reviewed: false,
  },
  '15.11': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '15.15': {
    theme: 'Wisdom & Knowledge',
    concepts: ['wisdom', 'knowledge'],
    reviewed: false,
  },
  '15.16': {
    theme: 'Impermanence & Soul',
    concepts: ['impermanence', 'soul'],
    reviewed: false,
  },
  '15.17': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person', 'unity'],
    reviewed: false,
  },
  '15.18': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person', 'transcendence', 'impermanence'],
    reviewed: false,
  },
  '15.19': {
    theme: 'Knowledge',
    concepts: ['knowledge'],
    reviewed: false,
  },
  '15.20': {
    theme: 'Purity & Wisdom',
    concepts: ['purity', 'wisdom', 'knowledge'],
    reviewed: false,
  },
  '16.2': {
    theme: 'Anger & Compassion',
    concepts: ['anger', 'compassion', 'renunciation'],
    reviewed: false,
  },
  '16.3': {
    theme: 'Ego & Purity',
    concepts: ['ego', 'purity'],
    reviewed: false,
  },
  '16.4': {
    theme: 'Ego & Anger',
    concepts: ['ego', 'anger', 'illusion'],
    reviewed: false,
  },
  '16.5': {
    theme: 'Bondage & Liberation',
    concepts: ['bondage', 'liberation', 'grief'],
    reviewed: false,
  },
  '16.7': {
    theme: 'Purity',
    concepts: ['purity'],
    reviewed: false,
  },
  '16.8': {
    theme: 'Desire & Unity',
    concepts: ['desire', 'unity'],
    reviewed: false,
  },
  '16.9': {
    theme: 'War',
    concepts: ['war'],
    reviewed: false,
  },
  '16.10': {
    theme: 'Ego & Illusion',
    concepts: ['ego', 'illusion'],
    reviewed: false,
  },
  '16.11': {
    theme: 'Death & Desire',
    concepts: ['death', 'desire'],
    reviewed: false,
  },
  '16.12': {
    theme: 'Desire & Anger',
    concepts: ['desire', 'anger', 'bondage'],
    reviewed: false,
  },
  '16.13': {
    theme: 'Desire',
    concepts: ['desire'],
    reviewed: false,
  },
  '16.14': {
    theme: 'War & Supreme Person',
    concepts: ['war', 'supreme-person', 'death'],
    reviewed: false,
  },
  '16.15': {
    theme: 'Illusion & Sacrifice',
    concepts: ['illusion', 'sacrifice', 'charity'],
    reviewed: false,
  },
  '16.16': {
    theme: 'Desire & Illusion',
    concepts: ['desire', 'illusion'],
    reviewed: false,
  },
  '16.17': {
    theme: 'Ego & Sacrifice',
    concepts: ['ego', 'sacrifice', 'soul'],
    reviewed: false,
  },
  '16.18': {
    theme: 'Anger & Desire',
    concepts: ['anger', 'desire', 'ego'],
    reviewed: false,
  },
  '16.20': {
    theme: 'Illusion',
    concepts: ['illusion'],
    reviewed: false,
  },
  '16.21': {
    theme: 'Desire & Anger',
    concepts: ['desire', 'anger', 'soul'],
    reviewed: false,
  },
  '16.22': {
    theme: 'Liberation',
    concepts: ['liberation'],
    reviewed: false,
  },
  '16.23': {
    theme: 'Desire & Self Realization',
    concepts: ['desire', 'self-realization'],
    reviewed: false,
  },
  '16.24': {
    theme: 'Duty & Action',
    concepts: ['duty', 'action'],
    reviewed: false,
  },
  '17.1': {
    theme: 'Modes Of Nature & Faith',
    concepts: ['modes-of-nature', 'faith', 'sacrifice'],
    reviewed: false,
  },
  '17.2': {
    theme: 'Modes Of Nature & Faith',
    concepts: ['modes-of-nature', 'faith', 'supreme-person', 'purity'],
    reviewed: false,
  },
  '17.4': {
    theme: 'Modes Of Nature & Illusion',
    concepts: ['modes-of-nature', 'illusion', 'devotion'],
    reviewed: false,
  },
  '17.5': {
    theme: 'Desire & Austerity',
    concepts: ['desire', 'austerity', 'attachment', 'ego'],
    reviewed: false,
  },
  '17.7': {
    theme: 'Austerity & Sacrifice',
    concepts: ['austerity', 'sacrifice'],
    reviewed: false,
  },
  '17.8': {
    theme: 'Purity & Modes Of Nature',
    concepts: ['purity', 'modes-of-nature'],
    reviewed: false,
  },
  '17.9': {
    theme: 'Modes Of Nature & Grief',
    concepts: ['modes-of-nature', 'grief'],
    reviewed: false,
  },
  '17.11': {
    theme: 'Sacrifice & Duty',
    concepts: ['sacrifice', 'duty', 'faith'],
    reviewed: false,
  },
  '17.12': {
    theme: 'Sacrifice & Modes Of Nature',
    concepts: ['sacrifice', 'modes-of-nature'],
    reviewed: false,
  },
  '17.13': {
    theme: 'Faith & Sacrifice',
    concepts: ['faith', 'sacrifice', 'modes-of-nature'],
    reviewed: false,
  },
  '17.14': {
    theme: 'Austerity & Purity',
    concepts: ['austerity', 'purity', 'devotion', 'guru'],
    reviewed: false,
  },
  '17.15': {
    theme: 'Austerity',
    concepts: ['austerity'],
    reviewed: false,
  },
  '17.16': {
    theme: 'Discipline & Austerity',
    concepts: ['discipline', 'austerity', 'purity', 'soul'],
    reviewed: false,
  },
  '17.17': {
    theme: 'Austerity & Faith',
    concepts: ['austerity', 'faith', 'modes-of-nature'],
    reviewed: false,
  },
  '17.18': {
    theme: 'Austerity & Impermanence',
    concepts: ['austerity', 'impermanence', 'modes-of-nature'],
    reviewed: false,
  },
  '17.19': {
    theme: 'Austerity & Illusion',
    concepts: ['austerity', 'illusion', 'modes-of-nature'],
    reviewed: false,
  },
  '17.20': {
    theme: 'Charity & Modes Of Nature',
    concepts: ['charity', 'modes-of-nature'],
    reviewed: false,
  },
  '17.21': {
    theme: 'Modes Of Nature & Charity',
    concepts: ['modes-of-nature', 'charity'],
    reviewed: false,
  },
  '17.22': {
    theme: 'Charity',
    concepts: ['charity'],
    reviewed: false,
  },
  '17.23': {
    theme: 'Sacrifice',
    concepts: ['sacrifice'],
    reviewed: false,
  },
  '17.24': {
    theme: 'Sacrifice & Austerity',
    concepts: ['sacrifice', 'austerity', 'charity'],
    reviewed: false,
  },
  '17.25': {
    theme: 'Sacrifice & Austerity',
    concepts: ['sacrifice', 'austerity', 'charity', 'liberation'],
    reviewed: false,
  },
  '17.26': {
    theme: 'Action',
    concepts: ['action'],
    reviewed: false,
  },
  '17.27': {
    theme: 'Austerity & Sacrifice',
    concepts: ['austerity', 'sacrifice', 'action', 'charity'],
    reviewed: false,
  },
  '17.28': {
    theme: 'Austerity & Faith',
    concepts: ['austerity', 'faith', 'sacrifice', 'charity'],
    reviewed: false,
  },
  '18.1': {
    theme: 'Renunciation & Desire',
    concepts: ['renunciation', 'desire'],
    reviewed: false,
  },
  '18.2': {
    theme: 'Renunciation & Wisdom',
    concepts: ['renunciation', 'wisdom', 'desire', 'knowledge'],
    reviewed: false,
  },
  '18.3': {
    theme: 'Sacrifice & Austerity',
    concepts: ['sacrifice', 'austerity', 'charity'],
    reviewed: false,
  },
  '18.4': {
    theme: 'Renunciation',
    concepts: ['renunciation'],
    reviewed: false,
  },
  '18.5': {
    theme: 'Austerity & Charity',
    concepts: ['austerity', 'charity', 'sacrifice', 'wisdom'],
    reviewed: false,
  },
  '18.6': {
    theme: 'Attachment',
    concepts: ['attachment'],
    reviewed: false,
  },
  '18.7': {
    theme: 'Renunciation & Illusion',
    concepts: ['renunciation', 'illusion', 'duty', 'modes-of-nature'],
    reviewed: false,
  },
  '18.8': {
    theme: 'Renunciation & Modes Of Nature',
    concepts: ['renunciation', 'modes-of-nature', 'action'],
    reviewed: false,
  },
  '18.9': {
    theme: 'Renunciation & Duty',
    concepts: ['renunciation', 'duty', 'action', 'attachment'],
    reviewed: false,
  },
  '18.10': {
    theme: 'Modes Of Nature & Wisdom',
    concepts: ['modes-of-nature', 'wisdom', 'purity', 'action'],
    reviewed: false,
  },
  '18.11': {
    theme: 'Renunciation & Action',
    concepts: ['renunciation', 'action', 'detachment'],
    reviewed: false,
  },
  '18.12': {
    theme: 'Renunciation & Death',
    concepts: ['renunciation', 'death', 'detachment'],
    reviewed: false,
  },
  '18.15': {
    theme: 'Action',
    concepts: ['action'],
    reviewed: false,
  },
  '18.16': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '18.17': {
    theme: 'Ego & Bondage',
    concepts: ['ego', 'bondage'],
    reviewed: false,
  },
  '18.18': {
    theme: 'Action & Knowledge',
    concepts: ['action', 'knowledge'],
    reviewed: false,
  },
  '18.19': {
    theme: 'Modes Of Nature & Knowledge',
    concepts: ['modes-of-nature', 'knowledge', 'action'],
    reviewed: false,
  },
  '18.20': {
    theme: 'Unity & Knowledge',
    concepts: ['unity', 'knowledge', 'soul', 'modes-of-nature'],
    reviewed: false,
  },
  '18.21': {
    theme: 'Knowledge & Unity',
    concepts: ['knowledge', 'unity', 'modes-of-nature'],
    reviewed: false,
  },
  '18.23': {
    theme: 'Attachment & Detachment',
    concepts: ['attachment', 'detachment', 'action', 'desire'],
    reviewed: false,
  },
  '18.24': {
    theme: 'Desire & Ego',
    concepts: ['desire', 'ego', 'action', 'modes-of-nature'],
    reviewed: false,
  },
  '18.25': {
    theme: 'Illusion & Action',
    concepts: ['illusion', 'action', 'modes-of-nature'],
    reviewed: false,
  },
  '18.26': {
    theme: 'Attachment & Ego',
    concepts: ['attachment', 'ego', 'modes-of-nature', 'purity'],
    reviewed: false,
  },
  '18.27': {
    theme: 'Grief & Modes Of Nature',
    concepts: ['grief', 'modes-of-nature'],
    reviewed: false,
  },
  '18.28': {
    theme: 'Grief',
    concepts: ['grief'],
    reviewed: false,
  },
  '18.29': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '18.30': {
    theme: 'Action & Bondage',
    concepts: ['action', 'bondage'],
    reviewed: false,
  },
  '18.31': {
    theme: 'Modes Of Nature & Dharma',
    concepts: ['modes-of-nature', 'dharma'],
    reviewed: false,
  },
  '18.32': {
    theme: 'Dharma',
    concepts: ['dharma'],
    reviewed: false,
  },
  '18.33': {
    theme: 'Modes Of Nature & Purity',
    concepts: ['modes-of-nature', 'purity'],
    reviewed: false,
  },
  '18.34': {
    theme: 'Desire & Modes Of Nature',
    concepts: ['desire', 'modes-of-nature', 'attachment', 'dharma'],
    reviewed: false,
  },
  '18.35': {
    theme: 'Grief & Ego',
    concepts: ['grief', 'ego', 'modes-of-nature'],
    reviewed: false,
  },
  '18.36': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '18.37': {
    theme: 'Wisdom & Self Realization',
    concepts: ['wisdom', 'self-realization', 'soul', 'modes-of-nature'],
    reviewed: false,
  },
  '18.38': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '18.39': {
    theme: 'Modes Of Nature',
    concepts: ['modes-of-nature'],
    reviewed: false,
  },
  '18.40': {
    theme: 'Modes Of Nature & Liberation',
    concepts: ['modes-of-nature', 'liberation'],
    reviewed: false,
  },
  '18.41': {
    theme: 'Duty & War',
    concepts: ['duty', 'war', 'modes-of-nature'],
    reviewed: false,
  },
  '18.42': {
    theme: 'Austerity & Discipline',
    concepts: ['austerity', 'discipline', 'knowledge', 'purity'],
    reviewed: false,
  },
  '18.43': {
    theme: 'War & Duty',
    concepts: ['war', 'duty', 'opulence'],
    reviewed: false,
  },
  '18.44': {
    theme: 'Duty & Action',
    concepts: ['duty', 'action'],
    reviewed: false,
  },
  '18.45': {
    theme: 'Duty & Self Realization',
    concepts: ['duty', 'self-realization'],
    reviewed: false,
  },
  '18.47': {
    theme: 'Duty',
    concepts: ['duty'],
    reviewed: false,
  },
  '18.48': {
    theme: 'Duty',
    concepts: ['duty'],
    reviewed: false,
  },
  '18.49': {
    theme: 'Renunciation & Detachment',
    concepts: ['renunciation', 'detachment', 'liberation'],
    reviewed: false,
  },
  '18.50': {
    theme: 'Supreme Person & Knowledge',
    concepts: ['supreme-person', 'knowledge', 'self-realization', 'soul'],
    reviewed: false,
  },
  '18.51': {
    theme: 'Purity & Attachment',
    concepts: ['purity', 'attachment'],
    reviewed: false,
  },
  '18.52': {
    theme: 'Meditation',
    concepts: ['meditation'],
    reviewed: false,
  },
  '18.53': {
    theme: 'Ego & Anger',
    concepts: ['ego', 'anger', 'desire', 'equanimity'],
    reviewed: false,
  },
  '18.54': {
    theme: 'Soul & Supreme Person',
    concepts: ['soul', 'supreme-person', 'devotion', 'unity'],
    reviewed: false,
  },
  '18.55': {
    theme: 'Devotion & Supreme Person',
    concepts: ['devotion', 'supreme-person'],
    reviewed: false,
  },
  '18.56': {
    theme: 'Soul & Grace',
    concepts: ['soul', 'grace', 'surrender'],
    reviewed: false,
  },
  '18.57': {
    theme: 'Surrender & Wisdom',
    concepts: ['surrender', 'wisdom', 'unity'],
    reviewed: false,
  },
  '18.58': {
    theme: 'Ego & Grace',
    concepts: ['ego', 'grace'],
    reviewed: false,
  },
  '18.59': {
    theme: 'Ego & War',
    concepts: ['ego', 'war', 'modes-of-nature'],
    reviewed: false,
  },
  '18.60': {
    theme: 'Illusion & Modes Of Nature',
    concepts: ['illusion', 'modes-of-nature'],
    reviewed: false,
  },
  '18.61': {
    theme: 'Unity',
    concepts: ['unity'],
    reviewed: false,
  },
  '18.62': {
    theme: 'Grace & Surrender',
    concepts: ['grace', 'surrender', 'equanimity', 'soul'],
    reviewed: false,
  },
  '18.63': {
    theme: 'Knowledge',
    concepts: ['knowledge'],
    reviewed: false,
  },
  '18.64': {
    theme: 'Supreme Person',
    concepts: ['supreme-person'],
    reviewed: false,
  },
  '18.65': {
    theme: 'Devotion & Sacrifice',
    concepts: ['devotion', 'sacrifice'],
    reviewed: false,
  },
  '18.67': {
    theme: 'Devotion & Austerity',
    concepts: ['devotion', 'austerity'],
    reviewed: false,
  },
  '18.68': {
    theme: 'Devotion',
    concepts: ['devotion'],
    reviewed: false,
  },
  '18.70': {
    theme: 'Knowledge & Sacrifice',
    concepts: ['knowledge', 'sacrifice', 'wisdom'],
    reviewed: false,
  },
  '18.71': {
    theme: 'Faith & Liberation',
    concepts: ['faith', 'liberation', 'dharma'],
    reviewed: false,
  },
  '18.72': {
    theme: 'Illusion',
    concepts: ['illusion'],
    reviewed: false,
  },
  '18.73': {
    theme: 'Illusion & Grace',
    concepts: ['illusion', 'grace'],
    reviewed: false,
  },
  '18.74': {
    theme: 'Soul',
    concepts: ['soul'],
    reviewed: false,
  },
  '18.75': {
    theme: 'Grace & Supreme Person',
    concepts: ['grace', 'supreme-person'],
    reviewed: false,
  },
  '18.77': {
    theme: 'Remembrance & Supreme Person',
    concepts: ['remembrance', 'supreme-person', 'universal-form'],
    reviewed: false,
  },
};
